"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Calculator, FileText, Layers3, Package, Plus, Save, Scissors, Settings2, Upload, WalletCards, X } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"; import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"; import { toast, Toaster } from "sonner";
import Link from "next/link";
type Supply={id:number;name:string;unit:string;unitValue:number;supplier:string;invoiceDate:string;invoiceNumber?:string}; type Cut={id:number;model:string;costPerPiece:number;totalCost:number;quantity:number;finishedAt:string}; type Sheet={id:number;reference:string;variant?:string;materials:{supplyId:number;quantity:number;unitValue:number}[];labor:{type:string;value:number}[];materialCost:number;laborCost:number;totalCost:number;simpleRate:number;cardRate:number;commissionRate:number;fixedExpenseRate:number;desiredProfitRate:number;currentPrice?:number}; type Data={supplies:Supply[];cuts:Cut[];sheets:Sheet[];variants:{model:string;color:string;size:string}[];settings:{simpleRate:number;cardRate:number;commissionRate:number;fixedExpenseRate:number}};
const brl=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}); const date=()=>new Date().toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"});
async function post(body:unknown){const r=await fetch("/api/production",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
export default function StockPricing(){
 const [data,setData]=useState<Data>({supplies:[],cuts:[],sheets:[],variants:[],settings:{simpleRate:0,cardRate:0,commissionRate:0,fixedExpenseRate:0}}); const [loading,setLoading]=useState(true); const [supplyFilter,setSupplyFilter]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/production");const d=await r.json();if(r.ok)setData(d);else toast.error(d.error);setLoading(false)},[]); useEffect(()=>{load()},[load]);
 const [supply,setSupply]=useState({name:"",unit:"metro",totalValue:"",totalQuantity:"1",supplier:"",invoiceDate:date(),invoiceNumber:"",observation:""}); const unitValue=Number(supply.totalValue)/(Number(supply.totalQuantity)||1);
 const [file,setFile]=useState<File|null>(null); const [uploading,setUploading]=useState(false);
 async function upload(){if(!file)return;setUploading(true);const f=new FormData();f.append("file",file);const r=await fetch("/api/production/upload",{method:"POST",body:f});const d=await r.json();if(r.ok)toast.success("Documento armazenado. Revise os dados do insumo abaixo.");else toast.error(d.error);setUploading(false)}
 async function saveSupply(e:FormEvent){e.preventDefault();try{await post({action:"supply",...supply,unitValue});toast.success("Insumo cadastrado.");setSupply({...supply,name:"",totalValue:"",totalQuantity:"1",invoiceNumber:"",observation:""});await load()}catch(e){toast.error((e as Error).message)}}
 const [days,setDays]=useState([{date:date(),dailyRate:""}]); const [cut,setCut]=useState({model:"",quantity:"",finishedAt:date()}); const cutTotal=days.reduce((s,d)=>s+Number(d.dailyRate||0),0); const cutPiece=cutTotal/(Number(cut.quantity)||1);
 async function saveCut(e:FormEvent){e.preventDefault();try{await post({action:"cut",...cut,quantity:Number(cut.quantity),workDays:days.map(d=>({...d,dailyRate:Number(d.dailyRate)}))});toast.success("Lote de corte finalizado.");setCut({model:"",quantity:"",finishedAt:date()});setDays([{date:date(),dailyRate:""}]);await load()}catch(e){toast.error((e as Error).message)}}
 const [sheet,setSheet]=useState({reference:"",variant:"",materials:[{supplyId:"",quantity:""}],labor:[{type:"Costureira",value:""}],desiredProfit:"30",practicedPrice:"",rates:{simple:"",card:"",commission:"",fixed:""}});
 const materials=sheet.materials.map(i=>{const s=data.supplies.find(x=>x.id===Number(i.supplyId));return{...i,unitValue:s?.unitValue||0,total:(s?.unitValue||0)*Number(i.quantity||0)}}); const materialCost=materials.reduce((s,i)=>s+i.total,0); const laborCost=sheet.labor.reduce((s,i)=>s+Number(i.value||0),0); const totalCost=materialCost+laborCost;
 const rates={simple:Number(sheet.rates.simple||data.settings.simpleRate),card:Number(sheet.rates.card||data.settings.cardRate),commission:Number(sheet.rates.commission||data.settings.commissionRate),fixed:Number(sheet.rates.fixed||data.settings.fixedExpenseRate)}; const rateSum=rates.simple+rates.card+rates.commission+rates.fixed+Number(sheet.desiredProfit||0); const calculated=rateSum<100?totalCost/(1-rateSum/100):0; const practiced=Number(sheet.practicedPrice||0); const realMargin=practiced?((practiced-totalCost-practiced*(rates.simple+rates.card+rates.commission+rates.fixed)/100)/practiced)*100:0;
 function selectCut(id:string){const c=data.cuts.find(x=>x.id===Number(id));if(c)setSheet({...sheet,labor:[...sheet.labor,{type:"Cortador",value:String(c.costPerPiece)}]})}
 async function saveSheet(e:FormEvent){e.preventDefault();try{const d=await post({action:"sheet",reference:sheet.reference,variant:sheet.variant,materials:materials.filter(i=>i.supplyId).map(i=>({supplyId:Number(i.supplyId),quantity:Number(i.quantity),unitValue:i.unitValue})),labor:sheet.labor.map(i=>({type:i.type,value:Number(i.value)})),rates,desiredProfit:Number(sheet.desiredProfit)});if(practiced>0)await post({action:"price",sheetId:d.row.id,practicedPrice:practiced,definedAt:date()});toast.success("Ficha técnica e precificação salvas.");await load()}catch(e){toast.error((e as Error).message)}}
 const filtered=data.supplies.filter(s=>`${s.name} ${s.supplier} ${s.invoiceDate}`.toLowerCase().includes(supplyFilter.toLowerCase()));
 return <div className="min-h-screen bg-[#f4f7fa] text-[#17304c]"><Toaster richColors position="top-right"/><aside className="fixed inset-y-0 left-0 hidden w-[268px] flex-col bg-[#14375f] text-white lg:flex"><div className="border-b border-white/10 px-7 py-6"><div className="text-[28px] font-black tracking-[-.04em]">CORETO</div><div className="text-[10px] font-semibold uppercase tracking-[.28em] text-[#65ddda]">Gestão interna</div></div><nav className="space-y-2 p-4"><Link prefetch href="/" className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm hover:bg-white/10"><ArrowLeft size={18}/>Recebimento da Facção</Link><div className="flex items-center gap-3 rounded-xl bg-[#147bc4] px-4 py-3 text-sm font-semibold"><Package size={18}/>Estoque & Precificação</div></nav><div className="mt-auto border-t border-white/10 p-6 text-xs text-blue-100/60">Acesso exclusivo do perfil Admin</div></aside>
 <main className="lg:ml-[268px]"><header className="border-b border-[#dce5ed] bg-white px-5 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1500px]"><Link prefetch href="/" className="mb-3 inline-flex items-center gap-2 text-xs font-semibold text-[#147bc4] lg:hidden"><ArrowLeft size={14}/>Recebimento</Link><p className="text-xs text-[#708398]">Operação / Custos e formação de preço</p><h1 className="mt-1 text-2xl font-black tracking-tight text-[#14375f]">Estoque & Precificação</h1></div></header>
 <div className="mx-auto max-w-[1500px] p-5 sm:p-8 lg:p-10"><section className="mb-6 grid gap-4 sm:grid-cols-3"><Metric icon={<Package/>} label="Insumos cadastrados" value={String(data.supplies.length)}/><Metric icon={<Layers3/>} label="Fichas técnicas" value={String(data.sheets.length)}/><Metric icon={<Scissors/>} label="Lotes de corte" value={String(data.cuts.length)}/></section>
 <Tabs defaultValue="supplies"><TabsList className="mb-6 h-auto w-full justify-start gap-1 overflow-x-auto rounded-xl border bg-white p-2"><TabsTrigger className="px-5 py-2.5 data-[state=active]:bg-[#14375f] data-[state=active]:text-white" value="supplies"><Package/>Central de Insumos</TabsTrigger><TabsTrigger className="px-5 py-2.5 data-[state=active]:bg-[#14375f] data-[state=active]:text-white" value="sheets"><FileText/>Fichas Técnicas</TabsTrigger><TabsTrigger className="px-5 py-2.5 data-[state=active]:bg-[#14375f] data-[state=active]:text-white" value="cuts"><Scissors/>Ficha de Corte</TabsTrigger></TabsList>
 <TabsContent value="supplies"><div className="grid items-start gap-6 xl:grid-cols-[430px_1fr]"><div className="space-y-6"><Card title="Importar nota ou comprovante" icon={<Upload/>}><Input type="file" accept="application/pdf,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><Input className="mt-3" placeholder="Fornecedor do documento" value={supply.supplier} onChange={e=>setSupply({...supply,supplier:e.target.value})}/><Button onClick={upload} disabled={!file||uploading} className="mt-3 w-full bg-[#20a8a5]">{uploading?"Enviando...":"Enviar e analisar documento"}</Button><p className="mt-2 text-xs text-[#8294a5]">PDF ou imagem. Os itens devem ser revisados antes do cadastro.</p></Card>
 <form onSubmit={saveSupply}><Card title="Cadastrar insumo" icon={<Plus/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome"><Input value={supply.name} onChange={e=>setSupply({...supply,name:e.target.value})} required/></Field><Field label="Unidade"><Select value={supply.unit} onValueChange={v=>setSupply({...supply,unit:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["metro","unidade","kg","rolo","pacote"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Valor total"><Input type="number" step="0.01" value={supply.totalValue} onChange={e=>setSupply({...supply,totalValue:e.target.value})} required/></Field><Field label="Quantidade comprada"><Input type="number" step="0.001" value={supply.totalQuantity} onChange={e=>setSupply({...supply,totalQuantity:e.target.value})} required/></Field><div className="sm:col-span-2 rounded-xl bg-[#e8f7f6] p-4"><p className="text-xs text-[#5d797a]">Custo unitário calculado</p><p className="text-xl font-black text-[#0e7775]">{brl(unitValue)} / {supply.unit}</p></div><Field label="Fornecedor"><Input value={supply.supplier} onChange={e=>setSupply({...supply,supplier:e.target.value})} required/></Field><Field label="Data da nota"><Input type="date" value={supply.invoiceDate} onChange={e=>setSupply({...supply,invoiceDate:e.target.value})}/></Field><Field label="Nº da nota"><Input value={supply.invoiceNumber} onChange={e=>setSupply({...supply,invoiceNumber:e.target.value})}/></Field><Field label="Observação"><Input value={supply.observation} onChange={e=>setSupply({...supply,observation:e.target.value})}/></Field><Button className="sm:col-span-2 bg-[#147bc4]"><Save/>Salvar insumo</Button></div></Card></form></div>
 <Card title="Central de Insumos" icon={<Package/>}><Input className="mb-4" placeholder="Filtrar por nome, fornecedor ou data" value={supplyFilter} onChange={e=>setSupplyFilter(e.target.value)}/><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Insumo</TableHead><TableHead>Unidade</TableHead><TableHead>Valor unitário</TableHead><TableHead>Fornecedor</TableHead><TableHead>Data</TableHead></TableRow></TableHeader><TableBody>{loading?<TableRow><TableCell colSpan={5}>Carregando...</TableCell></TableRow>:filtered.map(s=><TableRow key={s.id}><TableCell className="font-semibold">{s.name}</TableCell><TableCell>{s.unit}</TableCell><TableCell className="font-bold text-[#147bc4]">{brl(s.unitValue)}</TableCell><TableCell>{s.supplier}</TableCell><TableCell>{s.invoiceDate}</TableCell></TableRow>)}</TableBody></Table></div></Card></div></TabsContent>
 <TabsContent value="cuts"><div className="grid items-start gap-6 xl:grid-cols-[430px_1fr]"><form onSubmit={saveCut}><Card title="Novo lote de corte" icon={<Scissors/>}><div className="space-y-4"><Field label="Modelo / peça"><Input list="variants" value={cut.model} onChange={e=>setCut({...cut,model:e.target.value})} required/><datalist id="variants">{data.variants.map((v,i)=><option key={i} value={v.model}/>)}</datalist></Field><div><div className="mb-2 flex items-center justify-between"><Label>Dias trabalhados</Label><Button type="button" variant="outline" size="sm" onClick={()=>setDays([...days,{date:date(),dailyRate:""}])}><Plus/>Dia</Button></div>{days.map((d,i)=><div className="mb-2 flex gap-2" key={i}><Input type="date" value={d.date} onChange={e=>setDays(days.map((x,j)=>j===i?{...x,date:e.target.value}:x))}/><Input type="number" step=".01" placeholder="Diária R$" value={d.dailyRate} onChange={e=>setDays(days.map((x,j)=>j===i?{...x,dailyRate:e.target.value}:x))}/>{days.length>1&&<Button type="button" variant="ghost" onClick={()=>setDays(days.filter((_,j)=>j!==i))}><X/></Button>}</div>)}</div><Field label="Quantidade produzida"><Input type="number" value={cut.quantity} onChange={e=>setCut({...cut,quantity:e.target.value})}/></Field><Field label="Data de finalização"><Input type="date" value={cut.finishedAt} onChange={e=>setCut({...cut,finishedAt:e.target.value})}/></Field><div className="rounded-xl bg-[#14375f] p-4 text-white"><div className="flex justify-between text-sm"><span>Custo do lote</span><b>{brl(cutTotal)}</b></div><div className="mt-2 flex justify-between"><span>Corte por peça</span><b className="text-xl text-[#65ddda]">{brl(cutPiece)}</b></div></div><Button className="w-full bg-[#147bc4]"><Save/>Finalizar lote</Button></div></Card></form><Card title="Lotes finalizados" icon={<Scissors/>}><Table><TableHeader><TableRow><TableHead>Modelo</TableHead><TableHead>Data</TableHead><TableHead>Peças</TableHead><TableHead>Custo do lote</TableHead><TableHead>Por peça</TableHead></TableRow></TableHeader><TableBody>{data.cuts.map(c=><TableRow key={c.id}><TableCell className="font-semibold">{c.model}</TableCell><TableCell>{c.finishedAt}</TableCell><TableCell>{c.quantity}</TableCell><TableCell>{brl(c.totalCost)}</TableCell><TableCell className="font-bold text-[#147bc4]">{brl(c.costPerPiece)}</TableCell></TableRow>)}</TableBody></Table></Card></div></TabsContent>
 <TabsContent value="sheets"><div className="grid items-start gap-6 xl:grid-cols-[1fr_390px]"><form onSubmit={saveSheet}><Card title="Nova ficha técnica" icon={<FileText/>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome / referência"><Input list="models-sheet" value={sheet.reference} onChange={e=>setSheet({...sheet,reference:e.target.value})} required/><datalist id="models-sheet">{data.variants.map((v,i)=><option key={i} value={v.model}/>)}</datalist></Field><Field label="Variação recebida"><Select value={sheet.variant} onValueChange={v=>setSheet({...sheet,variant:v})}><SelectTrigger><SelectValue placeholder="Modelo · cor · tamanho"/></SelectTrigger><SelectContent>{data.variants.map((v,i)=><SelectItem key={i} value={`${v.model} · ${v.color} · ${v.size}`}>{v.model} · {v.color} · {v.size}</SelectItem>)}</SelectContent></Select></Field></div>
 <SectionTitle title="Materiais usados" action={()=>setSheet({...sheet,materials:[...sheet.materials,{supplyId:"",quantity:""}]})}/>{sheet.materials.map((m,i)=><div className="mb-3 grid gap-3 rounded-xl border p-3 sm:grid-cols-[1fr_130px_120px_40px]" key={i}><Select value={m.supplyId} onValueChange={v=>setSheet({...sheet,materials:sheet.materials.map((x,j)=>j===i?{...x,supplyId:v}:x)})}><SelectTrigger><SelectValue placeholder="Selecione o insumo"/></SelectTrigger><SelectContent>{data.supplies.map(s=><SelectItem key={s.id} value={String(s.id)}>{s.name} · {brl(s.unitValue)}/{s.unit}</SelectItem>)}</SelectContent></Select><Input type="number" step=".001" placeholder="Quantidade" value={m.quantity} onChange={e=>setSheet({...sheet,materials:sheet.materials.map((x,j)=>j===i?{...x,quantity:e.target.value}:x)})}/><div className="rounded-lg bg-[#f2f6f9] px-3 py-2 text-right font-bold">{brl(materials[i]?.total||0)}</div><Button type="button" variant="ghost" onClick={()=>setSheet({...sheet,materials:sheet.materials.filter((_,j)=>j!==i)})}><X/></Button></div>)}
 <SectionTitle title="Mão de obra" action={()=>setSheet({...sheet,labor:[...sheet.labor,{type:"Outro",value:""}]})}/><div className="mb-3"><Select onValueChange={selectCut}><SelectTrigger><SelectValue placeholder="Adicionar custo do cortador por lote"/></SelectTrigger><SelectContent>{data.cuts.map(c=><SelectItem key={c.id} value={String(c.id)}>{c.model} · {brl(c.costPerPiece)}/peça</SelectItem>)}</SelectContent></Select></div>{sheet.labor.map((l,i)=><div className="mb-3 grid gap-3 sm:grid-cols-[1fr_160px_40px]" key={i}><Input value={l.type} onChange={e=>setSheet({...sheet,labor:sheet.labor.map((x,j)=>j===i?{...x,type:e.target.value}:x)})}/><Input type="number" step=".01" placeholder="Valor" value={l.value} onChange={e=>setSheet({...sheet,labor:sheet.labor.map((x,j)=>j===i?{...x,value:e.target.value}:x)})}/><Button type="button" variant="ghost" onClick={()=>setSheet({...sheet,labor:sheet.labor.filter((_,j)=>j!==i)})}><X/></Button></div>)}
 <div className="mt-6 grid gap-4 sm:grid-cols-3"><Mini label="Material" value={brl(materialCost)}/><Mini label="Mão de obra" value={brl(laborCost)}/><Mini label="Custo total" value={brl(totalCost)} strong/></div>
 <SectionTitle title="Precificação"/><div className="grid gap-4 sm:grid-cols-3"><Field label="Simples %"><Input type="number" step=".01" placeholder={String(data.settings.simpleRate)} value={sheet.rates.simple} onChange={e=>setSheet({...sheet,rates:{...sheet.rates,simple:e.target.value}})}/></Field><Field label="Cartão %"><Input type="number" step=".01" placeholder={String(data.settings.cardRate)} value={sheet.rates.card} onChange={e=>setSheet({...sheet,rates:{...sheet.rates,card:e.target.value}})}/></Field><Field label="Comissão %"><Input type="number" step=".01" placeholder={String(data.settings.commissionRate)} value={sheet.rates.commission} onChange={e=>setSheet({...sheet,rates:{...sheet.rates,commission:e.target.value}})}/></Field><Field label="Despesas fixas %"><Input type="number" step=".01" placeholder={String(data.settings.fixedExpenseRate)} value={sheet.rates.fixed} onChange={e=>setSheet({...sheet,rates:{...sheet.rates,fixed:e.target.value}})}/></Field><Field label="Lucro desejado %"><Input type="number" step=".01" value={sheet.desiredProfit} onChange={e=>setSheet({...sheet,desiredProfit:e.target.value})}/></Field><Field label="Preço praticado"><Input type="number" step=".01" value={sheet.practicedPrice} onChange={e=>setSheet({...sheet,practicedPrice:e.target.value})}/></Field></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#e5f4fc] p-5"><p className="text-xs font-semibold text-[#55798f]">Preço de venda calculado</p><p className="mt-1 text-3xl font-black text-[#147bc4]">{rateSum>=100?"Taxas inválidas":brl(calculated)}</p></div><div className={`rounded-2xl p-5 ${realMargin<0?"bg-red-50 text-red-700":"bg-[#e6f8f6] text-[#0f7e7b]"}`}><p className="text-xs font-semibold">Margem de lucro real</p><p className="mt-1 text-3xl font-black">{realMargin.toFixed(2)}%</p></div></div><Button className="mt-6 w-full bg-[#147bc4]"><Save/>Salvar ficha e preço</Button></Card></form>
 <div className="space-y-6"><Settings data={data} reload={load}/><Card title="Fichas cadastradas" icon={<WalletCards/>}><div className="space-y-3">{data.sheets.length===0?<p className="text-sm text-[#8294a5]">Nenhuma ficha cadastrada.</p>:data.sheets.map(s=><div key={s.id} className="rounded-xl border p-4"><div className="flex items-start justify-between"><div><b>{s.reference}</b><p className="text-xs text-[#8294a5]">{s.variant||"Sem variação"}</p></div><span className="font-black text-[#147bc4]">{s.currentPrice?brl(s.currentPrice):"Sem preço"}</span></div><div className="mt-3 flex justify-between border-t pt-3 text-xs"><span>Custo total</span><b>{brl(s.totalCost)}</b></div></div>)}</div></Card></div></div></TabsContent>
 </Tabs></div></main></div>
}
function Card({title,icon,children}:{title:string;icon?:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border border-[#dfe7ee] bg-white shadow-sm"><header className="flex items-center gap-3 border-b px-5 py-4"><div className="text-[#147bc4]">{icon}</div><h2 className="font-bold text-[#14375f]">{title}</h2></header><div className="p-5">{children}</div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-2"><span className="text-sm font-medium">{label}</span>{children}</label>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex items-center gap-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="rounded-xl bg-[#e6f5fb] p-3 text-[#147bc4]">{icon}</div><div><p className="text-xs text-[#718598]">{label}</p><p className="text-2xl font-black text-[#14375f]">{value}</p></div></div>}
function Mini({label,value,strong}:{label:string;value:string;strong?:boolean}){return <div className={`rounded-xl p-4 ${strong?"bg-[#14375f] text-white":"bg-[#f2f6f9]"}`}><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function SectionTitle({title,action}:{title:string;action?:()=>void}){return <div className="mb-3 mt-7 flex items-center justify-between border-b pb-2"><h3 className="font-bold text-[#14375f]">{title}</h3>{action&&<Button type="button" size="sm" variant="outline" onClick={action}><Plus/>Adicionar</Button>}</div>}
function Settings({data,reload}:{data:Data;reload:()=>Promise<void>}){const [v,setV]=useState({simple:String(data.settings.simpleRate),card:String(data.settings.cardRate),commission:String(data.settings.commissionRate),fixed:String(data.settings.fixedExpenseRate)});useEffect(()=>setV({simple:String(data.settings.simpleRate),card:String(data.settings.cardRate),commission:String(data.settings.commissionRate),fixed:String(data.settings.fixedExpenseRate)}),[data.settings]);return <Dialog><DialogTrigger asChild><Button variant="outline" className="w-full"><Settings2/>Configurar taxas globais</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Taxas globais</DialogTitle><DialogDescription>Valores padrão usados em novas fichas. Eles podem ser sobrescritos por peça.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2">{Object.entries({simple:"Simples %",card:"Cartão %",commission:"Comissão %",fixed:"Despesas fixas %"}).map(([k,l])=><Field key={k} label={l}><Input type="number" step=".01" value={v[k as keyof typeof v]} onChange={e=>setV({...v,[k]:e.target.value})}/></Field>)}</div><Button className="bg-[#147bc4]" onClick={async()=>{try{await post({action:"settings",...Object.fromEntries(Object.entries(v).map(([k,x])=>[k,Number(x)]))});toast.success("Taxas atualizadas.");await reload()}catch(e){toast.error((e as Error).message)}}}><Save/>Salvar configurações</Button></DialogContent></Dialog>}
