import { and, desc, eq, gte, lt, lte } from "drizzle-orm";
import { getDb } from "@/db";
import { cutBatches, dailyFinance, employees, employeeWithdrawals, financialAdjustments, payrollClosures, receivables, salesRecords } from "@/db/schema";
export const dynamic = "force-dynamic"; const num=(v:unknown)=>Number(v)||0;
export async function GET(request:Request){try{const db=getDb(),u=new URL(request.url),date=u.searchParams.get("date")||new Date().toISOString().slice(0,10),month=u.searchParams.get("month")||date.slice(0,7);const monthEnd=`${month}-32`;const [people,withdrawals,payroll,financeRows,receivableRows,sales,cuts,adjustments]=await Promise.all([db.select().from(employees).orderBy(employees.name),db.select().from(employeeWithdrawals).orderBy(desc(employeeWithdrawals.withdrawnAt)),db.select().from(payrollClosures).orderBy(desc(payrollClosures.month)),db.select().from(dailyFinance).orderBy(desc(dailyFinance.date)),db.select().from(receivables).orderBy(desc(receivables.createdAt)),db.select().from(salesRecords).orderBy(desc(salesRecords.saleDate)),db.select().from(cutBatches).where(and(gte(cutBatches.finishedAt,`${month}-01`),lt(cutBatches.finishedAt,monthEnd))),db.select().from(financialAdjustments).orderBy(desc(financialAdjustments.date))]);return Response.json({employees:people.map(p=>({...p,tieredRates:JSON.parse(p.tieredRatesJson)})),withdrawals,payroll:payroll.map(p=>({...p,otherDiscounts:JSON.parse(p.otherDiscountsJson),details:JSON.parse(p.detailsJson)})),finance:financeRows.map(f=>({...f,paymentEntries:JSON.parse(f.paymentEntriesJson),flexibleAccounts:JSON.parse(f.flexibleAccountsJson),bankBalances:JSON.parse(f.bankBalancesJson)})),receivables:receivableRows.map(r=>({...r,dueDates:JSON.parse(r.dueDatesJson)})),sales,cuts,adjustments});}catch(e){return Response.json({error:e instanceof Error?e.message:"Falha ao carregar."},{status:500})}}
export async function POST(request:Request){try{const b=await request.json() as Record<string,unknown>,action=String(b.action),db=getDb();
 if(action==="employee"){const [row]=await db.insert(employees).values({name:String(b.name).trim(),jobTitle:String(b.jobTitle).trim(),active:b.active!==false,remunerationType:String(b.remunerationType||"commissioned"),baseSalary:num(b.baseSalary),commissionRate:num(b.commissionRate),transportAllowance:num(b.transportAllowance),costAllowance:num(b.costAllowance),dailyRate:num(b.dailyRate),tieredRatesJson:JSON.stringify(b.tieredRates||[])}).returning();return Response.json({row},{status:201})}
 if(action==="employee_update"){const id=num(b.id);await db.update(employees).set({remunerationType:String(b.remunerationType),baseSalary:num(b.baseSalary),commissionRate:num(b.commissionRate),transportAllowance:num(b.transportAllowance),costAllowance:num(b.costAllowance),dailyRate:num(b.dailyRate),tieredRatesJson:JSON.stringify(b.tieredRates||[])}).where(eq(employees.id,id));return Response.json({updated:true})}
 if(action==="withdrawal"){const [row]=await db.insert(employeeWithdrawals).values({employeeId:num(b.employeeId),itemName:String(b.itemName).trim(),chargedValue:num(b.chargedValue),withdrawnAt:String(b.withdrawnAt)}).returning();return Response.json({row},{status:201})}
 if(action==="finance"){const entries=Array.isArray(b.paymentEntries)?b.paymentEntries as {name:string;value:number}[]:[];const total=entries.reduce((s,x)=>s+num(x.value),0);const values={date:String(b.date),paymentEntriesJson:JSON.stringify(entries),flexibleAccountsJson:JSON.stringify(b.flexibleAccounts||[]),bankBalancesJson:JSON.stringify(b.bankBalances||[]),totalSales:total,updatedAt:new Date().toISOString()};const [existing]=await db.select().from(dailyFinance).where(eq(dailyFinance.date,String(b.date))).limit(1);if(existing)await db.update(dailyFinance).set(values).where(eq(dailyFinance.id,existing.id));else await db.insert(dailyFinance).values(values);return Response.json({total})}
 if(action==="receivable"){const total=num(b.totalValue),count=num(b.installments);const [row]=await db.insert(receivables).values({description:String(b.description),totalValue:total,installments:count,installmentValue:total/count,dueDatesJson:JSON.stringify(b.dueDates||[])}).returning();return Response.json({row},{status:201})}
 if(action==="adjustment"){const [row]=await db.insert(financialAdjustments).values({date:String(b.date),type:String(b.type),description:String(b.description).trim(),value:num(b.value)}).returning();return Response.json({row},{status:201})}
 if(action==="sales_import"){const records=Array.isArray(b.records)?b.records as {saleDate:string;sellerName:string;amount:number;category:string}[]:[],batch=crypto.randomUUID();for(const r of records){const person=await db.select().from(employees).where(eq(employees.name,r.sellerName)).limit(1);await db.insert(salesRecords).values({saleDate:r.saleDate,sellerName:r.sellerName,employeeId:person[0]?.id||null,amount:num(r.amount),category:r.category||"Sem categoria",importBatch:batch})}return Response.json({imported:records.length})}
 if(action==="payroll"){const employeeId=num(b.employeeId),month=String(b.month);const [person]=await db.select().from(employees).where(eq(employees.id,employeeId)).limit(1);if(!person)return Response.json({error:"Colaborador não encontrado."},{status:404});const [exists]=await db.select().from(payrollClosures).where(and(eq(payrollClosures.employeeId,employeeId),eq(payrollClosures.month,month))).limit(1);if(exists)return Response.json({error:"A folha deste colaborador já foi fechada neste mês."},{status:409});const salesValue=num(b.salesValue),storeSalesValue=num(b.storeSalesValue),bonus=num(b.bonusValue),withdrawalIds=(Array.isArray(b.withdrawalIds)?b.withdrawalIds:[]).map(num),other=Array.isArray(b.otherDiscounts)?b.otherDiscounts as {type:string;value:number;observation?:string}[]:[];let base=person.baseSalary,commission=0;if(person.remunerationType==="commissioned")commission=salesValue*person.commissionRate/100;if(person.remunerationType==="daily"){const cuts=await db.select().from(cutBatches).where(and(gte(cutBatches.finishedAt,`${month}-01`),lt(cutBatches.finishedAt,`${month}-32`)));base=cuts.reduce((s,c)=>s+num(c.totalCost),0)}if(person.remunerationType==="tiered"){const tiers=JSON.parse(person.tieredRatesJson) as {target:number;rate:number}[];const hit=tiers.filter(t=>storeSalesValue>=t.target).sort((a,b)=>b.target-a.target)[0];commission=storeSalesValue*num(hit?.rate)/100}let wd=0;for(const id of withdrawalIds){const [w]=await db.select().from(employeeWithdrawals).where(eq(employeeWithdrawals.id,id)).limit(1);if(w&&w.status==="pending")wd+=w.chargedValue}const otherValue=other.reduce((s,x)=>s+num(x.value),0),allowances=person.transportAllowance+person.costAllowance,net=base+commission+allowances+bonus-wd-otherValue;const [closure]=await db.insert(payrollClosures).values({employeeId,month,remunerationType:person.remunerationType,salesValue,storeSalesValue,baseValue:base,commissionValue:commission,allowancesValue:allowances,withdrawalDiscount:wd,otherDiscountsJson:JSON.stringify(other),otherDiscountsValue:otherValue,bonusValue:bonus,netValue:net,detailsJson:JSON.stringify({withdrawalIds})}).returning();for(const id of withdrawalIds)await db.update(employeeWithdrawals).set({status:"discounted",payrollClosureId:closure.id,discountedAt:new Date().toISOString()}).where(eq(employeeWithdrawals.id,id));return Response.json({closure})}
 return Response.json({error:"Ação inválida."},{status:400});}catch(e){return Response.json({error:e instanceof Error?e.message:"Falha ao salvar."},{status:500})}}
