"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Box, CalendarDays, Check, ChevronDown, ClipboardCheck, Filter, LogOut, Menu, PackageCheck, Plus, Search, Shirt, Sparkles, UserRound, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toast, Toaster } from "sonner";
import Link from "next/link";

type Receipt = { id: number; receivedAt: string; model: string; color: string; size: string; quantity: number; checkedBy: string; observation: string | null };
type User = { name: string; email: string | null; role: "admin" | "conferente" };
const sizes = ["PP", "P", "M", "G", "GG", "XG", "Único"];
const today = () => new Date().toLocaleDateString("en-CA", { timeZone: "America/Sao_Paulo" });
function shortDate(value: string) { const [y, m, d] = value.slice(0, 10).split("-"); return `${d}/${m}/${y}`; }

export default function Home() {
  const [receipts, setReceipts] = useState<Receipt[]>([]);
  const [user, setUser] = useState<User>({ name: "Usuário Coreto", email: null, role: "admin" });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [mobileNav, setMobileNav] = useState(false);
  const [form, setForm] = useState({ receivedAt: today(), model: "", color: "", size: "", quantity: "", observation: "" });
  const [filters, setFilters] = useState({ from: "", to: "", model: "", color: "" }); const [applied, setApplied] = useState(filters); const [suggestions, setSuggestions] = useState<string[]>([]);
  const load = useCallback(async () => {
    setLoading(true); const params = new URLSearchParams(); Object.entries(applied).forEach(([k, v]) => v && params.set(k, v));
    const response = await fetch(`/api/receipts?${params}`); const data = await response.json();
    if (response.ok) { setReceipts(data.receipts); setUser(data.user); setSuggestions(data.models); } else toast.error(data.error ?? "Não foi possível carregar os recebimentos."); setLoading(false);
  }, [applied]);
  useEffect(() => { load(); }, [load]);
  const total = useMemo(() => receipts.reduce((sum, item) => sum + item.quantity, 0), [receipts]);
  const weekTotal = useMemo(() => { const now = new Date(); const monday = new Date(now); monday.setDate(now.getDate() - ((now.getDay() + 6) % 7)); monday.setHours(0, 0, 0, 0); return receipts.filter((r) => new Date(`${r.receivedAt}T12:00:00`) >= monday).reduce((sum, r) => sum + r.quantity, 0); }, [receipts]);
  async function submit(event: FormEvent) {
    event.preventDefault(); if (!form.model.trim() || !form.color.trim() || !form.size || Number(form.quantity) < 1) { toast.error("Preencha modelo, cor, tamanho e uma quantidade válida."); return; }
    setSaving(true); const response = await fetch("/api/receipts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, quantity: Number(form.quantity) }) }); const data = await response.json();
    if (response.ok) { setForm((current) => ({ ...current, model: "", color: "", size: "", quantity: "", observation: "" })); toast.success("Recebimento registrado. Pronto para a próxima peça."); await load(); document.getElementById("model")?.focus(); } else toast.error(data.error ?? "Não foi possível salvar o registro."); setSaving(false);
  }
  return <div className="min-h-screen bg-[#f4f7fa] text-[#17304c]">
    <Toaster richColors position="top-right" />
    {mobileNav && <button className="fixed inset-0 z-30 bg-[#071c33]/45 lg:hidden" aria-label="Fechar menu" onClick={() => setMobileNav(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[268px] flex-col bg-[#14375f] text-white shadow-2xl transition-transform lg:translate-x-0 ${mobileNav ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-24 items-center justify-between border-b border-white/10 px-7"><div><div className="text-[28px] font-black tracking-[-.04em]">CORETO</div><div className="mt-0.5 text-[10px] font-semibold uppercase tracking-[.28em] text-[#65ddda]">Gestão interna</div></div><button className="lg:hidden" onClick={() => setMobileNav(false)} aria-label="Fechar menu"><X size={21} /></button></div>
      <nav className="flex-1 px-4 py-6"><div className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-blue-200/60">Operação</div><a className="flex items-center gap-3 rounded-xl bg-[#147bc4] px-4 py-3.5 text-sm font-semibold shadow-lg shadow-[#0b2847]/20" href="#top"><PackageCheck size={20} />Recebimento da Facção</a>{user.role === "admin" && <div className="mt-3 space-y-1">{[["/estoque-precificacao","Estoque & Precificação"],["/retiradas","Retiradas"],["/folha-comissao","Folha & Comissão"],["/fluxo-financeiro","Fluxo Financeiro"],["/vendas-comparativos","Vendas & Comparativos"]].map(([href,item]) => <Link prefetch href={href} key={href} className="flex items-center gap-3 rounded-xl px-4 py-2.5 text-sm hover:bg-white/10"><Box size={17} />{item}</Link>)}<div className="flex items-center gap-3 px-4 py-2.5 text-sm opacity-45"><Box size={17}/>Análise Financeira</div></div>}</nav>
      <div className="border-t border-white/10 p-4"><div className="flex items-center gap-3 rounded-xl bg-white/[.07] p-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#20c9c5] font-bold text-[#14375f]">{user.name.charAt(0).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{user.name}</div><div className="text-xs capitalize text-blue-100/65">{user.role}</div></div><LogOut size={16} className="text-blue-100/55" /></div></div>
    </aside>
    <main id="top" className="lg:ml-[268px]">
      <header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-[#dce5ed] bg-white/95 px-5 backdrop-blur sm:px-8 lg:px-10"><div className="flex items-center gap-3"><button className="rounded-lg border border-[#d7e1ea] p-2 lg:hidden" onClick={() => setMobileNav(true)} aria-label="Abrir menu"><Menu size={20} /></button><div><p className="text-xs font-medium text-[#708398]">Operação / Recebimento</p><h1 className="text-lg font-bold tracking-tight text-[#14375f] sm:text-xl">Recebimento da Facção</h1></div></div><div className="hidden items-center gap-2 rounded-full border border-[#dce5ed] bg-[#f8fafc] py-2 pl-2 pr-4 sm:flex"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#d9f8f6] text-[#128b8a]"><UserRound size={16} /></div><span className="text-sm font-semibold">{user.name}</span><ChevronDown size={14} className="text-[#7890a6]" /></div></header>
      <div className="mx-auto max-w-[1500px] space-y-6 p-5 sm:p-8 lg:p-10">
        <section className="grid gap-4 md:grid-cols-3"><div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-[#14375f] to-[#147bc4] p-6 text-white shadow-lg shadow-[#14375f]/10 md:col-span-2"><div className="absolute -right-8 -top-10 h-40 w-40 rounded-full border-[24px] border-white/[.06]" /><div className="relative flex items-start justify-between"><div><p className="text-sm font-medium text-blue-100">Peças recebidas nesta semana</p><p className="mt-2 text-4xl font-black tracking-tight">{weekTotal.toLocaleString("pt-BR")}</p><p className="mt-2 text-xs text-blue-100/75">Atualizado com os registros do histórico</p></div><div className="rounded-2xl bg-white/10 p-3"><Shirt size={28} /></div></div></div><div className="rounded-2xl border border-[#dfe7ee] bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-[#6a7f92]">Total no período filtrado</p><p className="mt-2 text-3xl font-black tracking-tight text-[#14375f]">{total.toLocaleString("pt-BR")}</p><p className="mt-2 text-xs text-[#8ca0b2]">{receipts.length} {receipts.length === 1 ? "registro" : "registros"}</p></div><div className="rounded-2xl bg-[#dff9f7] p-3 text-[#119a97]"><ClipboardCheck size={25} /></div></div></div></section>
        <section className="grid items-start gap-6 xl:grid-cols-[minmax(360px,0.82fr)_minmax(620px,1.45fr)]">
          <form onSubmit={submit} className="rounded-2xl border border-[#dfe7ee] bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-[#e5ecf2] px-6 py-5"><div className="rounded-xl bg-[#e3f3fc] p-2 text-[#147bc4]"><Plus size={20} /></div><div><h2 className="font-bold text-[#14375f]">Novo recebimento</h2><p className="text-xs text-[#8294a5]">Registre uma variação por vez</p></div></div><div className="grid gap-5 p-6 sm:grid-cols-2">
            <div className="space-y-2 sm:col-span-2"><Label htmlFor="date">Data do recebimento</Label><div className="relative"><CalendarDays className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8396a8]" size={17} /><Input id="date" type="date" className="h-11 pl-10" value={form.receivedAt} onChange={(e) => setForm({ ...form, receivedAt: e.target.value })} required /></div></div>
            <div className="space-y-2 sm:col-span-2"><Label htmlFor="model">Modelo</Label><Input id="model" list="models" className="h-11" placeholder="Ex.: Vestido Aurora" value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} autoComplete="off" required /><datalist id="models">{suggestions.map((model) => <option key={model} value={model} />)}</datalist></div>
            <div className="space-y-2"><Label htmlFor="color">Cor</Label><Input id="color" className="h-11" placeholder="Ex.: Azul marinho" value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} required /></div><div className="space-y-2"><Label>Tamanho</Label><Select value={form.size} onValueChange={(size) => setForm({ ...form, size })}><SelectTrigger className="h-11 w-full"><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{sizes.map((size) => <SelectItem key={size} value={size}>{size}</SelectItem>)}</SelectContent></Select></div>
            <div className="space-y-2 sm:col-span-2"><Label htmlFor="quantity">Quantidade contada</Label><Input id="quantity" className="h-11 text-base font-semibold" min="1" inputMode="numeric" type="number" placeholder="0" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} required /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="checkedBy">Conferido por</Label><Input id="checkedBy" className="h-11 bg-[#f4f7f9] text-[#5d7184]" value={user.name} disabled /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="observation">Observação <span className="font-normal text-[#96a6b4]">(opcional)</span></Label><Textarea id="observation" rows={3} placeholder="Ex.: veio a menos que o combinado" value={form.observation} onChange={(e) => setForm({ ...form, observation: e.target.value })} /></div><Button type="submit" disabled={saving} className="h-12 bg-[#147bc4] font-bold hover:bg-[#1069a8] sm:col-span-2">{saving ? "Salvando..." : <><Check size={18} />Salvar e adicionar outro</>}</Button>
          </div></form>
          <section className="min-w-0 rounded-2xl border border-[#dfe7ee] bg-white shadow-sm"><div className="border-b border-[#e5ecf2] p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-bold text-[#14375f]">Histórico de recebimentos</h2><p className="mt-0.5 text-xs text-[#8294a5]">Registros mais recentes primeiro</p></div><div className="flex items-center gap-2 text-xs font-semibold text-[#147bc4]"><Sparkles size={15} />Variações disponíveis para ficha técnica</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Input aria-label="Data inicial" type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} /><Input aria-label="Data final" type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })} /><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8a9baa]" size={15} /><Input className="pl-9" placeholder="Filtrar modelo" value={filters.model} onChange={(e) => setFilters({ ...filters, model: e.target.value })} /></div><div className="flex gap-2"><Input placeholder="Filtrar cor" value={filters.color} onChange={(e) => setFilters({ ...filters, color: e.target.value })} /><Button type="button" aria-label="Aplicar filtros" onClick={() => setApplied(filters)} className="shrink-0 bg-[#14375f]"><Filter size={16} /></Button></div></div>{Object.values(applied).some(Boolean) && <button className="mt-3 text-xs font-semibold text-[#147bc4] hover:underline" onClick={() => { const empty = { from: "", to: "", model: "", color: "" }; setFilters(empty); setApplied(empty); }}>Limpar filtros</button>}</div>
            <div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-[#f7f9fb]"><TableHead>Data</TableHead><TableHead>Modelo</TableHead><TableHead>Cor</TableHead><TableHead>Tam.</TableHead><TableHead className="text-right">Qtd.</TableHead><TableHead>Conferido por</TableHead><TableHead>Observação</TableHead></TableRow></TableHeader><TableBody>{loading ? <TableRow><TableCell colSpan={7} className="h-40 text-center text-[#7e91a2]">Carregando recebimentos...</TableCell></TableRow> : receipts.length === 0 ? <TableRow><TableCell colSpan={7} className="h-48 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#edf5fa] text-[#147bc4]"><PackageCheck /></div><p className="mt-3 font-semibold text-[#14375f]">Nenhum recebimento encontrado</p><p className="mt-1 text-xs text-[#8799a9]">Registre a primeira peça ou ajuste os filtros.</p></TableCell></TableRow> : receipts.map((item) => <TableRow key={item.id}><TableCell className="whitespace-nowrap text-[#617689]">{shortDate(item.receivedAt)}</TableCell><TableCell className="font-semibold text-[#14375f]">{item.model}</TableCell><TableCell>{item.color}</TableCell><TableCell><span className="rounded-md bg-[#e9f4fb] px-2 py-1 text-xs font-bold text-[#147bc4]">{item.size}</span></TableCell><TableCell className="text-right font-bold">{item.quantity}</TableCell><TableCell className="whitespace-nowrap">{item.checkedBy}</TableCell><TableCell className="max-w-[220px] truncate text-[#718598]" title={item.observation ?? ""}>{item.observation || "—"}</TableCell></TableRow>)}</TableBody></Table></div>
          </section>
        </section>
      </div>
    </main>
  </div>;
}
