import { env } from "cloudflare:workers";
import { accessError, getCurrentAccess } from "@/lib/access";
export const dynamic = "force-dynamic";

const amount = (value: string) => Number(value.replace(/[^\d,.-]/g, "").replace(/\./g, "").replace(",", ".")) || 0;
const isoDate = (value: string) => { const [day, month, rawYear] = value.split("/"); return `${rawYear.length === 2 ? `20${rawYear}` : rawYear}-${month}-${day}`; };
const reportMonth = (text: string) => { const match = text.match(/Periodo\s*:\s*(\d{2})\/(\d{2})\/(\d{4})/i); return match ? `${match[3]}-${match[2]}` : ""; };

function parseFirstPurchase(text: string) {
  const rows: Record<string, unknown>[] = [];
  for (const raw of text.split(/\r?\n/)) { const line = raw.replace(/\s+/g, " ").trim(); const match = line.match(/^(\d{2}\/\d{2}\/\d{4})\s+F\s+(\d+)\s+(.+?)\s+V\s+(.+?)\s+([A-Z]{2})\s+(\S+)\s+(.+?)\s+(\d+)\s+([\d.,]+)$/); if (!match) continue; const sellerAndName = splitSeller(match[3], match[7]); rows.push({ firstPurchaseAt: isoDate(match[1]), externalCode: match[2], name: sellerAndName.customer, city: match[4], state: match[5], phone: match[6], sellerName: sellerAndName.seller, piecesCount: Number(match[8]), totalSpent: amount(match[9]) }); }
  return rows;
}

function splitSeller(customerAndMaybeSeller: string, sellerColumn: string) { return { customer: customerAndMaybeSeller.trim(), seller: sellerColumn.trim() }; }

function parseBirthdays(text: string) {
  const rows: Record<string, unknown>[] = [], chunks = text.split(/(?=Código\s*\d+\s+Cliente\s*:)/i).slice(1);
  for (const chunk of chunks) { const externalCode = chunk.match(/^Código\s*(\d+)/i)?.[1] || "", name = chunk.match(/Cliente\s*:\s*(.*?)\s+Tipo\s*:/is)?.[1]?.replace(/\s+/g, " ").trim() || "", cpf = chunk.match(/C\.P\.F\s*\/\s*C\.P\.N\.J\s*:\s*([\d.-]+)/i)?.[1] || "", birth = chunk.match(/Data\s*Nasc\s*:\s*(\d{2}\/\d{2}\/\d{4})/i)?.[1] || "", phone = chunk.match(/Fone1\s*:\s*([^\s]*)/i)?.[1] || "", phone2 = chunk.match(/Fone2\s*:\s*([^\s]*)/i)?.[1] || "", city = chunk.match(/Cidade\s*:\s*(.*?)\s+UF\s*:/is)?.[1]?.replace(/\s+/g, " ").trim() || "", state = chunk.match(/UF\s*:\s*([A-Z]{2})/i)?.[1] || "", email = chunk.match(/E-mail\s*:\s*([^\s]*@[^\s]*)/i)?.[1] || ""; if (externalCode && name) rows.push({ externalCode, name, cpf, birthDate: birth ? isoDate(birth) : "", phone, phone2, city, state, email }); }
  return rows;
}

function parseSalesBySeller(text: string) {
  const rows: Record<string, unknown>[] = []; let seller = "";
  for (const raw of text.split(/\r?\n/)) { const line = raw.replace(/\s+/g, " ").trim(); const heading = line.match(/^Vendedor\s*:\s*(.+)$/i); if (heading) { seller = heading[1].trim(); continue; } const match = line.match(/^(\d+)\s+(\d{2}\/\d{2}\/\d{2})\s+\d+\s+(.+?)\s+([\d.]+,\d{2})\s+(-?[\d.]+,\d{2})\s+(DESCONTO|ACRESCIMO)\s+[\d.,]+%\s+(-?[\d.]+,\d{2})\s+([\d.]+,\d{2})$/i); if (!match || !seller) continue; const beforeValues = match[3], customerName = removeSellerSuffix(beforeValues, seller); rows.push({ saleCode: match[1], saleDate: isoDate(match[2]), customerName, sellerName: seller, productValue: amount(match[4]), exchangeValue: amount(match[5]), variationValue: amount(match[7]), amount: amount(match[8]) }); }
  return rows;
}

function removeSellerSuffix(value: string, seller: string) { const words = seller.split(/\s+/); for (let count = words.length; count >= 2; count--) { const candidate = words.slice(0, count).join(" "); const index = value.toUpperCase().lastIndexOf(candidate.toUpperCase()); if (index > 0) return value.slice(0, index).trim(); } return value.trim(); }

type PositionedText = { str: string; x: number; y: number };
type PdfDocument = { numPages: number; getPage: (page: number) => Promise<{ getTextContent: () => Promise<{ items: unknown[] }> }> };
async function positionedRows(pdf: PdfDocument) { const pages: PositionedText[][][] = []; for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber++) { const page = await pdf.getPage(pageNumber), content = await page.getTextContent(), byY = new Map<number, PositionedText[]>(); for (const raw of content.items) { const item = raw as { str?: string; transform?: number[] }; if (!item.str?.trim() || !item.transform) continue; const value = { str: item.str.trim(), x: item.transform[4], y: item.transform[5] }, key = Math.round(value.y); byY.set(key, [...(byY.get(key) || []), value]); } pages.push([...byY.values()].map((row) => row.sort((a,b) => a.x-b.x)).sort((a,b) => b[0].y-a[0].y)); } return pages; }
const at = (row: PositionedText[], min: number, max: number) => row.find((item) => item.x >= min && item.x < max)?.str || "";
async function parseFirstPurchasePdf(pdf: PdfDocument) { const output: Record<string, unknown>[] = []; for (const page of await positionedRows(pdf)) for (const row of page) { const date = at(row, 10, 45), code = at(row, 85, 120); if (!/^\d{2}\/\d{2}\/\d{4}$/.test(date) || !/^\d+$/.test(code)) continue; output.push({ firstPurchaseAt: isoDate(date), externalCode: code, name: at(row, 120, 265), city: at(row, 280, 390), state: at(row, 390, 415), phone: at(row, 415, 540), sellerName: at(row, 540, 755), piecesCount: Number(at(row, 755, 800)), totalSpent: amount(at(row, 800, 840)) }); } return output; }
async function parseBirthdaysPdf(pdf: PdfDocument) { const output: Record<string, unknown>[] = []; for (const page of await positionedRows(pdf)) for (let index = 0; index < page.length; index++) { const codeRow = page[index], codeItem = codeRow.find((item) => item.x >= 45 && item.x < 100 && /^\d{4,6}$/.test(item.str)); if (!codeItem) continue; const header = page.filter((row) => Math.abs(row[0].y-codeItem.y) <= 2).flat().sort((a,b) => a.x-b.x), name = at(header, 100, 405), cpf = at(header, 530, 665); if (!name || !/[\d.-]{8,}/.test(cpf)) continue; const address = page.find((row) => codeItem.y-row[0].y > 10 && codeItem.y-row[0].y < 18) || [], phoneRow = page.find((row) => codeItem.y-row[0].y > 25 && codeItem.y-row[0].y < 33) || [], birth = at(address, 720, 840); output.push({ externalCode: codeItem.str, name, cpf, city: at(address, 390, 500), state: at(address, 495, 535), birthDate: /^\d{2}\/\d{2}\/\d{4}$/.test(birth) ? isoDate(birth) : "", phone: at(phoneRow, 150, 380) }); } return output; }
async function parseSalesPdf(pdf: PdfDocument) { const output: Record<string, unknown>[] = []; for (const page of await positionedRows(pdf)) { let seller = ""; for (const row of page) { const heading = row.find((item) => item.str === "Vendedor :"); if (heading) { seller = row.find((item) => item.x > heading.x + 35)?.str || seller; continue; } const code = at(row, 10, 45), date = at(row, 45, 80); if (!/^\d{6}$/.test(code) || !/^\d{2}\/\d{2}\/\d{2}$/.test(date) || !seller) continue; const exchange = at(row, 380, 455).match(/-?[\d.]+,\d{2}/)?.[0] || "0"; output.push({ saleCode: code, saleDate: isoDate(date), customerName: at(row, 90, 235), sellerName: seller, productValue: amount(at(row, 330, 385)), exchangeValue: amount(exchange), variationValue: amount(at(row, 490, 550)), amount: amount(at(row, 545, 595)) }); } } return output; }

export async function POST(request: Request) { try { const access = await getCurrentAccess(); const denied = accessError(access, ["admin","vendedora"]); if (denied) return denied; const form = await request.formData(), file = form.get("file"); if (!(file instanceof File) || file.type !== "application/pdf") return Response.json({ error: "Selecione um relatório em PDF." }, { status: 400 }); if (file.size > 15 * 1024 * 1024) return Response.json({ error: "O PDF deve ter no máximo 15 MB." }, { status: 400 }); const bytes = new Uint8Array(await file.arrayBuffer()), key = `crm-reports/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; await env.BUCKET.put(key, bytes, { httpMetadata: { contentType: file.type } }); const { extractText, getDocumentProxy } = await import("unpdf"); const pdf = await getDocumentProxy(bytes) as PdfDocument; const result = await extractText(pdf, { mergePages: true }); const text = typeof result.text === "string" ? result.text : result.text.join("\n"); let reportType = "", rows: Record<string, unknown>[] = [], label = ""; if (/Primeira Compra/i.test(text)) { reportType = "first_purchase"; rows = await parseFirstPurchasePdf(pdf); label = "Clientes - Primeira compra"; } else if (/Relatório de Desconto\s*\/\s*Acréscimo de Vendas/i.test(text)) { reportType = "sales_by_seller"; rows = await parseSalesPdf(pdf); label = "Vendas agrupadas por vendedor"; } else if (/Relatório de Clientes/i.test(text) && /Data\s*Nasc/i.test(text)) { reportType = "birthdays"; rows = await parseBirthdaysPdf(pdf); label = "Aniversariantes"; } if (!rows.length) return Response.json({ error: "Não consegui reconhecer os dados deste relatório. Confira se é um dos três modelos do CRM." }, { status: 422 }); return Response.json({ reportType, label, reportMonth: reportMonth(text), rows, fileName: file.name, key }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao ler o relatório." }, { status: 500 }); } }
