import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, sqliteView, text } from "drizzle-orm/sqlite-core";
export const receipts = sqliteTable("receipts", { id: integer("id").primaryKey({ autoIncrement: true }), receivedAt: text("received_at").notNull(), model: text("model").notNull(), color: text("color").notNull(), size: text("size").notNull(), quantity: integer("quantity").notNull(), checkedBy: text("checked_by").notNull(), checkedByEmail: text("checked_by_email"), observation: text("observation"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const productVariantSuggestions = sqliteView("product_variant_suggestions", { model: text("model"), color: text("color"), size: text("size"), lastReceivedAt: text("last_received_at"), totalReceived: integer("total_received") }).as(sql`SELECT model, color, size, MAX(received_at) AS last_received_at, SUM(quantity) AS total_received FROM receipts GROUP BY model, color, size`);

export const supplies = sqliteTable("supplies", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), unit: text("unit").notNull(), unitValue: real("unit_value").notNull(), supplier: text("supplier").notNull(), invoiceDate: text("invoice_date").notNull(), invoiceNumber: text("invoice_number"), observation: text("observation"), sourceFileKey: text("source_file_key"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const cutBatches = sqliteTable("cut_batches", { id: integer("id").primaryKey({ autoIncrement: true }), model: text("model").notNull(), workDaysJson: text("work_days_json").notNull(), totalCost: real("total_cost").notNull(), quantity: integer("quantity").notNull(), costPerPiece: real("cost_per_piece").notNull(), finishedAt: text("finished_at").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const technicalSheets = sqliteTable("technical_sheets", { id: integer("id").primaryKey({ autoIncrement: true }), reference: text("reference").notNull(), variant: text("variant"), materialsJson: text("materials_json").notNull(), laborJson: text("labor_json").notNull(), materialCost: real("material_cost").notNull(), laborCost: real("labor_cost").notNull(), totalCost: real("total_cost").notNull(), simpleRate: real("simple_rate").notNull().default(0), cardRate: real("card_rate").notNull().default(0), commissionRate: real("commission_rate").notNull().default(0), fixedExpenseRate: real("fixed_expense_rate").notNull().default(0), desiredProfitRate: real("desired_profit_rate").notNull().default(0), currentPrice: real("current_price"), pricedAt: text("priced_at"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const priceHistory = sqliteTable("price_history", { id: integer("id").primaryKey({ autoIncrement: true }), technicalSheetId: integer("technical_sheet_id").notNull().references(() => technicalSheets.id), practicedPrice: real("practiced_price").notNull(), realMarginRate: real("real_margin_rate").notNull(), definedAt: text("defined_at").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const pricingSettings = sqliteTable("pricing_settings", { id: integer("id").primaryKey(), simpleRate: real("simple_rate").notNull().default(0), cardRate: real("card_rate").notNull().default(0), commissionRate: real("commission_rate").notNull().default(0), fixedExpenseRate: real("fixed_expense_rate").notNull().default(0), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) });

export const employees = sqliteTable("employees", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), jobTitle: text("job_title").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true), remunerationType: text("remuneration_type").notNull().default("commissioned"), baseSalary: real("base_salary").notNull().default(0), commissionRate: real("commission_rate").notNull().default(0), transportAllowance: real("transport_allowance").notNull().default(0), costAllowance: real("cost_allowance").notNull().default(0), dailyRate: real("daily_rate").notNull().default(0), tieredRatesJson: text("tiered_rates_json").notNull().default("[]"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const employeeWithdrawals = sqliteTable("employee_withdrawals", { id: integer("id").primaryKey({ autoIncrement: true }), employeeId: integer("employee_id").notNull().references(() => employees.id), itemName: text("item_name").notNull(), chargedValue: real("charged_value").notNull(), withdrawnAt: text("withdrawn_at").notNull(), status: text("status").notNull().default("pending"), payrollClosureId: integer("payroll_closure_id"), discountedAt: text("discounted_at"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const payrollClosures = sqliteTable("payroll_closures", { id: integer("id").primaryKey({ autoIncrement: true }), employeeId: integer("employee_id").notNull().references(() => employees.id), month: text("month").notNull(), remunerationType: text("remuneration_type").notNull(), salesValue: real("sales_value").notNull().default(0), storeSalesValue: real("store_sales_value").notNull().default(0), baseValue: real("base_value").notNull().default(0), commissionValue: real("commission_value").notNull().default(0), allowancesValue: real("allowances_value").notNull().default(0), withdrawalDiscount: real("withdrawal_discount").notNull().default(0), otherDiscountsJson: text("other_discounts_json").notNull().default("[]"), otherDiscountsValue: real("other_discounts_value").notNull().default(0), bonusValue: real("bonus_value").notNull().default(0), netValue: real("net_value").notNull(), detailsJson: text("details_json").notNull().default("{}"), closedAt: text("closed_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const dailyFinance = sqliteTable("daily_finance", { id: integer("id").primaryKey({ autoIncrement: true }), date: text("date").notNull().unique(), paymentEntriesJson: text("payment_entries_json").notNull().default("[]"), flexibleAccountsJson: text("flexible_accounts_json").notNull().default("[]"), bankBalancesJson: text("bank_balances_json").notNull().default("[]"), totalSales: real("total_sales").notNull().default(0), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const receivables = sqliteTable("receivables", { id: integer("id").primaryKey({ autoIncrement: true }), description: text("description").notNull(), totalValue: real("total_value").notNull(), installments: integer("installments").notNull(), installmentValue: real("installment_value").notNull(), dueDatesJson: text("due_dates_json").notNull(), receivedInstallments: integer("received_installments").notNull().default(0), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const salesRecords = sqliteTable("sales_records", { id: integer("id").primaryKey({ autoIncrement: true }), saleDate: text("sale_date").notNull(), employeeId: integer("employee_id").references(() => employees.id), sellerName: text("seller_name").notNull(), amount: real("amount").notNull(), category: text("category").notNull(), importBatch: text("import_batch").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const financialAdjustments = sqliteTable("financial_adjustments", { id: integer("id").primaryKey({ autoIncrement: true }), date: text("date").notNull(), type: text("type").notNull(), description: text("description").notNull(), value: real("value").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
