import { asc, eq, sql } from "drizzle-orm";
import { getDb } from "@/db";
import { appUsers } from "@/db/schema";
import { accessError, ensureBootstrapAdmin } from "@/lib/access";
export const dynamic = "force-dynamic";

export async function GET() { try { const access = await ensureBootstrapAdmin(); const denied = accessError(access, ["admin"]); if (denied) return denied; const users = await getDb().select().from(appUsers).orderBy(asc(appUsers.name)); return Response.json({ users, currentUser: access }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao carregar usuários." }, { status: 500 }); } }
export async function POST(request: Request) { try { const access = await ensureBootstrapAdmin(); const denied = accessError(access, ["admin"]); if (denied) return denied; const body = await request.json() as Record<string, unknown>; const email = String(body.email || "").trim().toLowerCase(), name = String(body.name || "").trim(), role = String(body.role || "vendedora"), sellerName = String(body.sellerName || "").trim() || null; if (!email.includes("@") || !name || !["admin","chefe","conferente","vendedora"].includes(role)) return Response.json({ error: "Preencha nome, e-mail e perfil corretamente." }, { status: 400 }); const db = getDb(); const [row] = await db.insert(appUsers).values({ email, name, role, sellerName: role === "vendedora" ? sellerName : null, active: body.active !== false }).onConflictDoUpdate({ target: appUsers.email, set: { name, role, sellerName: role === "vendedora" ? sellerName : null, active: body.active !== false, updatedAt: sql`CURRENT_TIMESTAMP` } }).returning(); return Response.json({ row }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao salvar usuário." }, { status: 500 }); } }
export async function PUT(request: Request) { try { const access = await ensureBootstrapAdmin(); const denied = accessError(access, ["admin"]); if (denied) return denied; const body = await request.json() as Record<string, unknown>; const id = Number(body.id); if (!id) return Response.json({ error: "Usuário inválido." }, { status: 400 }); await getDb().update(appUsers).set({ active: body.active !== false, updatedAt: sql`CURRENT_TIMESTAMP` }).where(eq(appUsers.id, id)); return Response.json({ updated: true }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao atualizar usuário." }, { status: 500 }); } }
