"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowUpRight, BadgePercent, CalendarRange, CircleDollarSign, Plus, TrendingUp, Wallet } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CoreShell, Panel, isoToday, money } from "@/components/core-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast, Toaster } from "sonner";

type Sale={saleDate:string;amount:number}; type Finance={date:string;flexibleAccounts:{name:string;value:number}[]}; type Receivable={installmentValue:number;receivedInstallments:number;dueDates:string[]}; type Adjustment={id:number;date:string;type:string;description:string;value:number}; type Sheet={totalCost:number;currentPrice?:number};
async function send(body:unknown){const r=await fetch("/api/core",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
export default function Analysis(){const now=new Date(),initialFrom=new Date(now.getFullYear(),now.getMonth(),1).toLocaleDateString("en-CA"),initialTo=new Date(now.getFullYear(),now.getMonth()+1,0).toLocaleDateString("en-CA");const[period,setPeriod]=useState({from:initialFrom,to:initialTo}),[sales,setSales]=useState<Sale[]>([]),[finance,setFinance]=useState<Finance[]>([]),[receivables,setReceivables]=useState<Receivable[]>([]),[adjustments,setAdjustments]=useState<Adjustment[]>([]),[sheets,setSheets]=useState<Sheet[]>([]),[form,setForm]=useState({date:isoToday(),type:"expense",description:"",value:""});const load=useCallback(async()=>{const[a,b]=await Promise.all([fetch("/api/core"),fetch("/api/production")]);const core=await a.json(),prod=await b.json();if(a.ok){setSales(core.sales);setFinance(core.finance);setReceivables(core.receivables);setAdjustments(core.adjustments||[])}if(b.ok)setSheets(prod.sheets||[])},[]);useEffect(()=>{load()},[load]);
 const current=sales.filter(s=>s.saleDate>=period.from&&s.saleDate<=period.to),revenue=current.reduce((s,x)=>s+x.amount,0),days=Math.max(1,(new Date(period.to).getTime()-new Date(period.from).getTime())/86400000+1);const prevTo=new Date(new Date(period.from).getTime()-86400000),prevFrom=new Date(prevTo.getTime()-(days-1)*86400000),prev=sales.filter(s=>new Date(s.saleDate)>=prevFrom&&new Date(s.saleDate)<=prevTo),prevRevenue=prev.reduce((s,x)=>s+x.amount,0),growth=prevRevenue?((revenue-prevRevenue)/prevRevenue)*100:0;const avgCostRatio=(()=>{const priced=sheets.filter(s=>s.currentPrice&&s.currentPrice>0);return priced.length?priced.reduce((sum,s)=>sum+s.totalCost/(s.currentPrice||1),0)/priced.length:0})();const estimatedCmv=revenue*avgCostRatio;const flowExpenses=finance.filter(f=>f.date>=period.from&&f.date<=period.to).flatMap(f=>f.flexibleAccounts).reduce((s,x)=>s+Number(x.value||0),0),manualExpense=adjustments.filter(a=>a.type==="expense"&&a.date>=period.from&&a.date<=period.to).reduce((s,a)=>s+a.value,0),manualIncome=adjustments.filter(a=>a.type==="income"&&a.date>=period.from&&a.date<=period.to).reduce((s,a)=>s+a.value,0),adjustedRevenue=revenue+manualIncome,totalExpenses=flowExpenses+manualExpense,grossProfit=adjustedRevenue-estimatedCmv,netProfit=grossProfit-totalExpenses,grossMargin=adjustedRevenue?grossProfit/adjustedRevenue*100:0,netMargin=adjustedRevenue?netProfit/adjustedRevenue*100:0,ticket=current.length?revenue/current.length:0,fixedShare=adjustedRevenue?totalExpenses/adjustedRevenue*100:0;
 const monthly=useMemo(()=>{const map:Record<string,number>={};sales.forEach(s=>{const m=s.saleDate.slice(0,7);map[m]=(map[m]||0)+s.amount});return Object.entries(map).sort().slice(-6).map(([month,value])=>({month:month.slice(5)+"/"+month.slice(2,4),value}))},[sales]);const averageMonthly=monthly.length?monthly.reduce((s,x)=>s+x.value,0)/monthly.length:0;const projection=[0,1,2].map(offset=>{const d=new Date(now.getFullYear(),now.getMonth()+offset,1),key=d.toLocaleDateString("en-CA").slice(0,7),receivable=receivables.reduce((sum,r)=>sum+r.dueDates.filter((due,i)=>i>=r.receivedInstallments&&due.startsWith(key)).length*r.installmentValue,0);return{month:d.toLocaleDateString("pt-BR",{month:"short"}),sales:averageMonthly,receivable,total:averageMonthly+receivable}});const composition=[{name:"CMV estimado",value:estimatedCmv,color:"#147bc4"},{name:"Despesas",value:totalExpenses,color:"#20c9c5"},{name:"Lucro líquido",value:Math.max(0,netProfit),color:"#14375f"}];async function save(e:FormEvent){e.preventDefault();try{await send({action:"adjustment",...form,value:Number(form.value)});toast.success("Ajuste incluído na análise.");setForm({...form,description:"",value:""});await load()}catch(x){toast.error((x as Error).message)}}
 return <CoreShell active="/analise-financeira" title="Análise Financeira" subtitle="Gestão / Saúde financeira"><Toaster richColors/><div className="mb-6 flex flex-wrap items-end gap-3 rounded-2xl border bg-white p-5"><label className="space-y-2"><Label>Início do período</Label><Input type="date" value={period.from} onChange={e=>setPeriod({...period,from:e.target.value})}/></label><label className="space-y-2"><Label>Fim do período</Label><Input type="date" value={period.to} onChange={e=>setPeriod({...period,to:e.target.value})}/></label><div className="ml-auto flex items-center gap-2 rounded-xl bg-[#e7f5fb] px-4 py-3 text-sm font-semibold text-[#147bc4]"><CalendarRange size={18}/>{current.length} vendas analisadas</div></div>
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Receita ajustada" value={money(adjustedRevenue)} detail={`${growth>=0?"+":""}${growth.toFixed(1)}% vs. período anterior`} icon={<CircleDollarSign/>} good={growth>=0}/><Metric label="Margem bruta" value={`${grossMargin.toFixed(1)}%`} detail={`Lucro bruto ${money(grossProfit)}`} icon={<BadgePercent/>}/><Metric label="Margem líquida" value={`${netMargin.toFixed(1)}%`} detail={`Resultado ${money(netProfit)}`} icon={<Activity/>} good={netMargin>=0}/><Metric label="Ticket médio" value={money(ticket)} detail={`${current.length} lançamentos de venda`} icon={<Wallet/>}/></div>
 <div className="grid gap-6 xl:grid-cols-2"><Panel title="Receita dos últimos meses"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly}><defs><linearGradient id="sales" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#147bc4" stopOpacity={.4}/><stop offset="95%" stopColor="#147bc4" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e5edf3"/><XAxis dataKey="month"/><YAxis hide/><Tooltip formatter={(v)=>money(Number(v))}/><Area type="monotone" dataKey="value" stroke="#147bc4" strokeWidth={3} fill="url(#sales)"/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Como a receita está sendo distribuída"><div className="grid items-center gap-3 sm:grid-cols-2"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={composition} dataKey="value" innerRadius={58} outerRadius={90} paddingAngle={3}>{composition.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip formatter={(v)=>money(Number(v))}/></PieChart></ResponsiveContainer></div><div className="space-y-3">{composition.map(x=><div key={x.name} className="flex items-center justify-between rounded-xl border p-3"><span className="flex items-center gap-2"><i className="h-3 w-3 rounded-full" style={{background:x.color}}/>{x.name}</span><b>{money(x.value)}</b></div>)}<div className="rounded-xl bg-[#f4f7fa] p-3"><p className="text-xs text-[#708398]">Despesas x receita</p><b className="text-xl text-[#14375f]">{fixedShare.toFixed(1)}%</b></div></div></div></Panel></div>
 <div className="mt-6 grid items-start gap-6 xl:grid-cols-[1.35fr_.65fr]"><Panel title="Fluxo de caixa projetado"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={projection}><CartesianGrid vertical={false} stroke="#e5edf3"/><XAxis dataKey="month"/><YAxis hide/><Tooltip formatter={(v)=>money(Number(v))}/><Bar dataKey="sales" name="Vendas estimadas" stackId="a" fill="#147bc4" radius={[0,0,5,5]}/><Bar dataKey="receivable" name="Parcelas a receber" stackId="a" fill="#20c9c5" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="grid gap-3 sm:grid-cols-3">{projection.map(x=><div key={x.month} className="rounded-xl bg-[#f4f7fa] p-3"><p className="text-xs capitalize text-[#708398]">{x.month}</p><b className="text-lg text-[#14375f]">{money(x.total)}</b></div>)}</div></Panel><form onSubmit={save}><Panel title="Ajuste manual"><div className="space-y-4"><label className="space-y-2"><Label>Data</Label><Input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label className="space-y-2"><Label>Tipo</Label><Select value={form.type} onValueChange={v=>setForm({...form,type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="expense">Despesa adicional</SelectItem><SelectItem value="income">Receita adicional</SelectItem></SelectContent></Select></label><label className="space-y-2"><Label>Descrição</Label><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Ex.: manutenção pontual" required/></label><label className="space-y-2"><Label>Valor</Label><Input type="number" step=".01" value={form.value} onChange={e=>setForm({...form,value:e.target.value})} required/></label><Button className="w-full bg-[#147bc4]"><Plus/>Incluir na análise</Button></div></Panel></form></div>
 <div className="mt-6"><Panel title="Leitura do período"><div className="grid gap-4 md:grid-cols-3"><Insight title="Rentabilidade" text={netMargin>=10?`A margem líquida está em ${netMargin.toFixed(1)}%, indicando resultado positivo no período.`:netMargin>=0?`A operação está positiva, mas a margem de ${netMargin.toFixed(1)}% pede atenção aos custos.`:`O período apresenta resultado negativo de ${money(Math.abs(netProfit))}.`}/><Insight title="Despesas" text={`As despesas registradas consomem ${fixedShare.toFixed(1)}% da receita ajustada.`}/><Insight title="Projeção" text={`A projeção média mensal, somada às parcelas a receber, parte de ${money(averageMonthly)} em vendas históricas.`}/></div></Panel></div></CoreShell>}
function Metric({label,value,detail,icon,good=true}:{label:string;value:string;detail:string;icon:React.ReactNode;good?:boolean}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-[#708398]">{label}</p><p className="mt-2 text-3xl font-black text-[#14375f]">{value}</p></div><div className="rounded-xl bg-[#e7f5fb] p-3 text-[#147bc4]">{icon}</div></div><p className={`mt-3 text-xs font-semibold ${good?"text-emerald-600":"text-red-600"}`}>{detail}</p></div>}function Insight({title,text}:{title:string;text:string}){return <div className="rounded-xl border-l-4 border-[#20c9c5] bg-[#f7fafc] p-4"><b className="text-[#14375f]">{title}</b><p className="mt-2 text-sm leading-6 text-[#617688]">{text}</p></div>}
