"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart3, FileClock, FileText, PackageCheck, ReceiptText, Trash2, TrendingDown, TrendingUp, Trophy, Upload } from "lucide-react";
import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts";
import { CoreShell, Panel, money } from "@/components/core-shell";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toast, Toaster } from "sonner";

type Sale = { id: number; saleDate: string; sellerName: string; amount: number; category: string; quantity?: number; saleCount?: number; commissionValue?: number; recordType?: string; reportMonth?: string; sourceFileName?: string; importBatch?: string; createdAt?: string };
type Row = Record<string, string>;
type Mapping = { date: string; seller: string; amount: string; category: string; quantity: string; saleCount: string; commission: string };
const emptyMapping: Mapping = { date: "", seller: "", amount: "", category: "", quantity: "", saleCount: "", commission: "" };
const currentMonth = () => new Date().toLocaleDateString("en-CA", { timeZone: "America/Sao_Paulo" }).slice(0, 7);
const monthName = (month: string) => new Date(`${month}-02T12:00:00`).toLocaleDateString("pt-BR", { month: "long", year: "numeric" });
const dayLabel = (value: string) => value ? `${value.slice(8, 10)}/${value.slice(5, 7)}` : "—";
const numberValue = (value = "") => { const cleaned = String(value).trim().replace(/[^0-9,.-]/g, ""); const normalized = cleaned.includes(",") ? cleaned.replace(/\./g, "").replace(",", ".") : cleaned; return Number(normalized) || 0; };
const sum = (rows: Sale[], field: "amount" | "quantity" | "saleCount") => rows.reduce((total, row) => total + Number(row[field] || 0), 0);

async function send(body: unknown) { const response = await fetch("/api/core", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
function parseCsv(text: string) { const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean), separator = (lines[0]?.split(";").length || 0) > (lines[0]?.split(",").length || 0) ? ";" : ","; const parse = (line: string) => { const output: string[] = [], expression = new RegExp(`(?:^|${separator})(?:"([^"]*(?:""[^"]*)*)"|([^${separator}]*))`, "g"); let match; while ((match = expression.exec(line))) output.push((match[1] ?? match[2] ?? "").replace(/""/g, '"').trim()); return output; }; const headers = parse(lines[0]); return lines.slice(1).map((line) => Object.fromEntries(parse(line).map((value, index) => [headers[index] || `Coluna ${index + 1}`, value]))); }
function suggestedMapping(rows: Row[]): Mapping { const headers = Object.keys(rows[0] || {}), find = (terms: string[]) => headers.find((header) => terms.some((term) => header.toLowerCase().includes(term))) || ""; return { date: find(["data", "date"]), seller: find(["vended", "seller", "colaborador", "descrição"]), amount: find(["valor", "total", "amount"]), category: find(["modelo", "categoria", "produto", "descrição"]), quantity: find(["quant", "peças", "pecas", "itens"]), saleCount: find(["vendas", "pedidos", "atendimentos", "cupons"]), commission: find(["comissão", "comissao", "commission"]) }; }
function normalizeDate(value: string, month: string) { if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return value; const match = value.match(/^(\d{2})[/.\-](\d{2})(?:[/.\-](\d{2,4}))?$/); if (!match) return `${month}-01`; const year = match[3] ? (match[3].length === 2 ? `20${match[3]}` : match[3]) : month.slice(0, 4); return `${year}-${match[2]}-${match[1]}`; }

export default function Sales() {
  const [sales, setSales] = useState<Sale[]>([]), [raw, setRaw] = useState<Row[]>([]), [mapping, setMapping] = useState<Mapping>(emptyMapping);
  const [month, setMonth] = useState(currentMonth()), [reportType, setReportType] = useState("detailed"), [sourceFileName, setSourceFileName] = useState(""), [reading, setReading] = useState(false), [importing, setImporting] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/core"), data = await response.json(); if (response.ok) setSales(data.sales || []); }, []);
  useEffect(() => { load(); }, [load]);

  async function readFile(file: File) { setReading(true); setRaw([]); setSourceFileName(file.name); try { let rows: Row[] = [], recognized = ""; if (file.name.toLowerCase().endsWith(".pdf")) { const form = new FormData(); form.append("file", file); const response = await fetch("/api/sales/upload", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); rows = data.rows; recognized = data.label; if (data.detectedType) setReportType(data.detectedType); if (data.month) setMonth(data.month); } else if (file.name.toLowerCase().endsWith(".csv")) rows = parseCsv(await file.text()); else throw new Error("Envie um arquivo PDF ou CSV."); setRaw(rows); setMapping(suggestedMapping(rows)); toast.success(recognized ? `${recognized} reconhecido: ${rows.length} registros prontos para conferir.` : `${rows.length} linhas identificadas. Revise antes de importar.`); } catch (error) { toast.error((error as Error).message); } finally { setReading(false); } }
  async function importRows() { if (!mapping.amount) return toast.error("Selecione a coluna que contém o valor vendido."); setImporting(true); try { const records = raw.map((row) => { const saleDate = normalizeDate(mapping.date ? row[mapping.date] || "" : "", month); return { saleDate, sellerName: mapping.seller ? row[mapping.seller] || "Não informado" : "Não informado", amount: numberValue(row[mapping.amount]), category: mapping.category ? row[mapping.category] || "Sem categoria" : "Sem categoria", quantity: mapping.quantity ? numberValue(row[mapping.quantity]) : reportType === "detailed" ? 1 : 0, saleCount: mapping.saleCount ? numberValue(row[mapping.saleCount]) : reportType === "detailed" ? 1 : 0, commissionValue: mapping.commission ? numberValue(row[mapping.commission]) : 0, recordType: reportType, reportMonth: saleDate.slice(0, 7), sourceFileName }; }).filter((row) => row.amount > 0 || row.quantity > 0 || row.saleCount > 0); if (!records.length) throw new Error("Nenhuma linha válida foi encontrada. Revise o mapeamento."); const data = await send({ action: "sales_import", records }); toast.success(`${data.imported} linhas importadas.`); setRaw([]); setMapping(emptyMapping); await load(); } catch (error) { toast.error((error as Error).message); } finally { setImporting(false); } }
  const analysis = useMemo(() => buildAnalysis(sales, month), [sales, month]);
  const imports = useMemo(() => buildImportHistory(sales), [sales]);
  async function deleteImport(importBatch: string) { try { await send({ action: "sales_import_delete", importBatch }); toast.success("Importação excluída."); await load(); } catch (error) { toast.error((error as Error).message); } }

  return <CoreShell active="/vendas-comparativos" title="Vendas & Comparativos" subtitle={`Comercial / ${monthName(month)}`}><Toaster richColors/>
    <div className="mb-5 flex flex-col gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:flex-row sm:items-end sm:justify-between"><label className="space-y-2"><Label>Mês analisado</Label><Input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="w-full sm:w-52"/></label><p className="max-w-xl text-sm text-[#708398]">Os indicadores e rankings mudam automaticamente conforme o mês selecionado.</p></div>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Hero label="Total vendido no período" value={money(analysis.total)} icon={<BarChart3/>}/><Hero label="Quantidade de vendas" value={analysis.salesCount.toLocaleString("pt-BR")} icon={<ReceiptText/>}/><Hero label="Quantidade de peças" value={analysis.pieces.toLocaleString("pt-BR")} icon={<PackageCheck/>}/><Hero label="Comparação com mês anterior" value={`${analysis.variation >= 0 ? "+" : ""}${analysis.variation.toFixed(1)}%`} detail={analysis.previousTotal ? `Anterior: ${money(analysis.previousTotal)}` : "Sem dados anteriores"} icon={analysis.variation >= 0 ? <TrendingUp/> : <TrendingDown/>}/></div>
    <div className="mb-6 grid items-start gap-6 xl:grid-cols-[430px_1fr]"><Panel title="Importar relatórios"><div className="space-y-4"><label className="space-y-2"><Label>Tipo de informação do arquivo</Label><Select value={reportType} onValueChange={setReportType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="detailed">Vendas detalhadas</SelectItem><SelectItem value="daily">Resumo de vendas por dia</SelectItem><SelectItem value="products">Produtos / peças vendidas</SelectItem><SelectItem value="sellers">Vendas por vendedora</SelectItem><SelectItem value="annual">Resumo geral do ano</SelectItem></SelectContent></Select></label><label className="flex cursor-pointer flex-col items-center rounded-xl border-2 border-dashed border-[#b9ccdb] p-7 text-center transition hover:bg-[#f5fafc]"><FileText className="mb-2 text-[#159C85]" size={36}/><b>{reading ? "Lendo o relatório..." : "Selecionar PDF ou CSV"}</b><span className="mt-1 text-xs text-[#7c90a1]">Você pode enviar os relatórios separados</span><input className="hidden" type="file" accept=".pdf,.csv,application/pdf,text/csv" disabled={reading} onChange={(event) => event.target.files?.[0] && readFile(event.target.files[0])}/></label></div>{raw.length > 0 && <div className="mt-5 border-t pt-5"><h3 className="mb-3 font-bold text-[#16324A]">Identificar as colunas</h3><div className="grid gap-3 sm:grid-cols-2">{Object.entries({ date: "Data", seller: "Vendedora", amount: "Valor vendido", category: "Peça / produto", quantity: "Quantidade de peças", saleCount: "Quantidade de vendas", commission: "Comissão" }).map(([key, label]) => <MapField key={key} label={label} value={mapping[key as keyof Mapping]} headers={Object.keys(raw[0])} set={(value) => setMapping({ ...mapping, [key]: value === "__none" ? "" : value })}/>)}</div><Button className="mt-4 w-full bg-[#159C85]" disabled={importing} onClick={importRows}><Upload/>{importing ? "Importando..." : "Confirmar importação"}</Button></div>}</Panel><Panel title="Pré-visualização do relatório"><div className="overflow-x-auto"><Table><TableHeader><TableRow>{Object.keys(raw[0] || {}).slice(0, 6).map((header) => <TableHead key={header}>{header}</TableHead>)}</TableRow></TableHeader><TableBody>{raw.slice(0, 8).map((row, index) => <TableRow key={index}>{Object.keys(raw[0] || {}).slice(0, 6).map((header) => <TableCell key={header} className="max-w-56 truncate">{row[header]}</TableCell>)}</TableRow>)}</TableBody></Table>{raw.length === 0 && <div className="py-14 text-center"><FileText className="mx-auto mb-3 text-[#a6b7c4]"/><p className="text-sm text-[#7d90a1]">Selecione um PDF ou CSV para conferir as informações antes da importação.</p></div>}</div></Panel></div>
    <div className="mb-6"><Panel title={`Vendas mensais de ${month.slice(0, 4)}`}><ChartContainer config={{ value: { label: "Vendas", color: "#159C85" } }} className="h-[320px] w-full"><BarChart data={analysis.months}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis hide/><ChartTooltip content={<ChartTooltipContent formatter={(value) => money(Number(value))}/>}/><Bar dataKey="value" fill="#159C85" radius={[7,7,0,0]}/></BarChart></ChartContainer></Panel></div>
    <div className="grid gap-6 xl:grid-cols-2"><Panel title="Dias com mais vendas"><Ranking empty="Ainda não há vendas por dia neste mês." rows={analysis.days.map((row) => ({ name: dayLabel(row.date), value: money(row.value), note: `${row.count} vendas · ${row.pieces} peças` }))}/></Panel><Panel title="5 peças mais vendidas"><Ranking empty="Importe o relatório de produtos para montar este ranking." rows={analysis.products.map((row) => ({ name: row.name, value: `${row.pieces} peças`, note: row.value ? money(row.value) : undefined }))}/></Panel></div>
    <div className="mt-6"><Panel title="Ranking por vendedora"><Ranking empty="Importe o relatório de vendas por vendedora." rows={analysis.sellers.map((row) => ({ name: row.name, value: money(row.value), note: `${row.count} vendas · ${money(row.commission)} de comissão` }))}/></Panel></div>
    <div className="mt-6"><ImportHistory imports={imports} onDelete={deleteImport}/></div>
  </CoreShell>;
}

function buildAnalysis(sales: Sale[], month: string) {
  const rowsForMonth = (target: string) => sales.filter((row) => (row.reportMonth || row.saleDate.slice(0, 7)) === target);
  const byType = (rows: Sale[], type: string) => rows.filter((row) => (row.recordType || "detailed") === type);
  const firstAvailable = (rows: Sale[], types: string[]) => { for (const type of types) { const selected = byType(rows, type); if (selected.length) return selected; } return [] as Sale[]; };
  const rows = rowsForMonth(month);
  const totals = firstAvailable(rows, ["annual", "daily", "detailed"]);
  const dayRows = firstAvailable(rows, ["daily", "detailed"]);
  const productRows = firstAvailable(rows, ["products", "detailed"]);
  const sellerRows = firstAvailable(rows, ["sellers", "detailed"]);
  const previousDate = new Date(`${month}-02T12:00:00`); previousDate.setMonth(previousDate.getMonth() - 1);
  const previousMonth = previousDate.toLocaleDateString("en-CA").slice(0, 7);
  const previousTotals = firstAvailable(rowsForMonth(previousMonth), ["annual", "daily", "detailed"]);
  const total = sum(totals, "amount"), previousTotal = sum(previousTotals, "amount"), variation = previousTotal ? ((total - previousTotal) / previousTotal) * 100 : 0;
  const productPieces = sum(productRows, "quantity"), totalPieces = sum(totals, "quantity");
  const dayMap = dayRows.reduce((output, row) => { const value = output[row.saleDate] || { value: 0, count: 0, pieces: 0 }; value.value += row.amount; value.count += Number(row.saleCount || 0); value.pieces += Number(row.quantity || 0); output[row.saleDate] = value; return output; }, {} as Record<string, { value: number; count: number; pieces: number }>);
  const productMap = productRows.reduce((output, row) => { const value = output[row.category] || { pieces: 0, value: 0 }; value.pieces += Number(row.quantity || 0); value.value += row.amount; output[row.category] = value; return output; }, {} as Record<string, { pieces: number; value: number }>);
  const sellerMap = sellerRows.reduce((output, row) => { const value = output[row.sellerName] || { value: 0, count: 0, commission: 0 }; value.value += row.amount; value.count += Number(row.saleCount || 0); value.commission += Number(row.commissionValue || 0); output[row.sellerName] = value; return output; }, {} as Record<string, { value: number; count: number; commission: number }>);
  const months = Array.from({ length: 12 }, (_, index) => { const key = `${month.slice(0, 4)}-${String(index + 1).padStart(2, "0")}`; return { name: new Date(`${key}-02T12:00:00`).toLocaleDateString("pt-BR", { month: "short" }).replace(".", ""), value: sum(firstAvailable(rowsForMonth(key), ["annual", "daily", "detailed"]), "amount") }; });
  return { total, previousTotal, variation, salesCount: sum(totals, "saleCount"), pieces: productPieces || totalPieces, months,
    days: Object.entries(dayMap).map(([date, values]) => ({ date, ...values })).sort((a,b) => b.value-a.value).slice(0,5),
    products: Object.entries(productMap).map(([name, values]) => ({ name, ...values })).filter((row) => row.name !== "Sem categoria").sort((a,b) => b.pieces-a.pieces || b.value-a.value).slice(0,5),
    sellers: Object.entries(sellerMap).map(([name, values]) => ({ name, ...values })).filter((row) => row.name !== "Não informado").sort((a,b) => b.value-a.value),
  };
}
function Hero({ label, value, detail, icon }: { label: string; value: string; detail?: string; icon: React.ReactNode }) { return <div className="flex items-start justify-between rounded-2xl border bg-white p-5 shadow-sm"><div><p className="text-xs text-[#708398]">{label}</p><p className="mt-2 text-2xl font-black text-[#16324A]">{value}</p>{detail && <p className="mt-1 text-xs text-[#8294a5]">{detail}</p>}</div><div className="rounded-xl bg-[#e7f5fb] p-3 text-[#159C85]">{icon}</div></div>; }
function MapField({ label, value, headers, set }: { label: string; value: string; headers: string[]; set: (value: string) => void }) { return <label className="space-y-1"><Label>{label}</Label><Select value={value || "__none"} onValueChange={set}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__none">Não usar</SelectItem>{headers.map((header) => <SelectItem key={header} value={header}>{header}</SelectItem>)}</SelectContent></Select></label>; }
function Ranking({ rows, empty }: { rows: { name: string; value: string; note?: string }[]; empty: string }) { if (!rows.length) return <p className="rounded-xl border border-dashed py-10 text-center text-sm text-[#7d90a1]">{empty}</p>; return <div className="space-y-3">{rows.map((row, index) => <div key={`${row.name}-${index}`} className="flex items-center gap-4 rounded-xl border p-4"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-full font-black ${index < 3 ? "bg-[#16324A] text-white" : "bg-[#edf3f7]"}`}>{index + 1}</div><div className="min-w-0 flex-1"><b className="block truncate text-[#16324A]">{row.name}</b>{row.note && <span className="text-xs text-[#7d90a1]">{row.note}</span>}</div><b className="text-right text-[#159C85]">{row.value}</b>{index === 0 && <Trophy className="hidden text-[#20a8a5] sm:block" size={20}/>}</div>)}</div>; }

type ImportGroup = { importBatch: string; fileName: string; recordType: string; months: string[]; records: number; createdAt: string };
function buildImportHistory(sales: Sale[]) { const groups = new Map<string, ImportGroup & { monthSet: Set<string> }>(); for (const row of sales) { if (!row.importBatch) continue; const existing = groups.get(row.importBatch) || { importBatch: row.importBatch, fileName: row.sourceFileName || "Importação sem nome", recordType: row.recordType || "detailed", months: [], monthSet: new Set<string>(), records: 0, createdAt: row.createdAt || "" }; existing.monthSet.add(row.reportMonth || row.saleDate.slice(0, 7)); existing.records += 1; const rowCreatedAt = row.createdAt || ""; if (rowCreatedAt > existing.createdAt) existing.createdAt = rowCreatedAt; groups.set(row.importBatch, existing); } return [...groups.values()].map(({ monthSet, ...group }) => ({ ...group, months: [...monthSet].sort() })).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
function ImportHistory({ imports, onDelete }: { imports: ImportGroup[]; onDelete: (importBatch: string) => Promise<void> }) { return <Panel title="Histórico de importações"><div className="mb-4 flex items-center gap-3 rounded-xl bg-[#E9F9F5] p-4"><FileClock className="shrink-0 text-[#159C85]"/><p className="text-sm text-[#587185]">Exclua somente o arquivo que precisa corrigir. Os demais relatórios continuarão salvos.</p></div>{imports.length === 0 ? <p className="rounded-xl border border-dashed py-10 text-center text-sm text-[#7d90a1]">Nenhum arquivo importado.</p> : <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Arquivo</TableHead><TableHead>Tipo</TableHead><TableHead>Período</TableHead><TableHead>Registros</TableHead><TableHead>Importado em</TableHead><TableHead className="text-right">Ação</TableHead></TableRow></TableHeader><TableBody>{imports.map((item) => <TableRow key={item.importBatch}><TableCell className="max-w-64 font-semibold text-[#16324A]"><span className="block truncate">{item.fileName}</span></TableCell><TableCell>{reportTypeLabel(item.recordType)}</TableCell><TableCell>{monthRange(item.months)}</TableCell><TableCell>{item.records}</TableCell><TableCell>{formatImportDate(item.createdAt)}</TableCell><TableCell className="text-right"><DeleteImportButton item={item} onDelete={onDelete}/></TableCell></TableRow>)}</TableBody></Table></div>}</Panel>; }
function DeleteImportButton({ item, onDelete }: { item: ImportGroup; onDelete: (importBatch: string) => Promise<void> }) { return <AlertDialog><AlertDialogTrigger asChild><Button size="sm" variant="outline" className="border-red-200 text-red-600 hover:bg-red-50 hover:text-red-700"><Trash2/>Excluir</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir esta importação?</AlertDialogTitle><AlertDialogDescription>Os dados do arquivo “{item.fileName}” serão removidos dos cards, gráficos e rankings. Esta ação não pode ser desfeita.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => onDelete(item.importBatch)}><Trash2/>Excluir importação</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }
function reportTypeLabel(type: string) { return ({ detailed: "Vendas detalhadas", daily: "Vendas por dia", products: "Produtos vendidos", sellers: "Comissão por vendedor", annual: "Resumo anual" } as Record<string, string>)[type] || "Relatório"; }
function monthRange(months: string[]) { if (!months.length) return "—"; const label = (value: string) => `${value.slice(5, 7)}/${value.slice(0, 4)}`; return months.length === 1 ? label(months[0]) : `${label(months[0])} a ${label(months.at(-1) || months[0])}`; }
function formatImportDate(value: string) { if (!value) return "—"; const parsed = new Date(value.includes("T") ? value : `${value.replace(" ", "T")}Z`); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo", dateStyle: "short", timeStyle: "short" }); }
