import { and, asc, desc, eq, like, lte, or, sql } from "drizzle-orm";
import { getDb } from "@/db";
import { crmCustomers, crmImports, crmInteractions, crmSales } from "@/db/schema";
import { accessError, getCurrentAccess } from "@/lib/access";
export const dynamic = "force-dynamic";
const num = (value: unknown) => Number(value) || 0;
const text = (value: unknown) => String(value || "").trim();
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^A-Za-z0-9]/g, "").toUpperCase();

export async function GET(request: Request) { try { const access = await getCurrentAccess(); const denied = accessError(access, ["admin","vendedora"]); if (denied || !access) return denied!; const db = getDb(), url = new URL(request.url), search = url.searchParams.get("search")?.trim(); const conditions = []; if (access.role === "vendedora") { if (!access.sellerName) return Response.json({ error: "Seu usuário ainda não está vinculado ao nome da vendedora." }, { status: 403 }); conditions.push(eq(crmCustomers.responsibleSeller, access.sellerName)); } if (search) conditions.push(or(like(crmCustomers.name, `%${search}%`), like(crmCustomers.phone, `%${search}%`), like(crmCustomers.externalCode, `%${search}%`))!); const customers = await db.select().from(crmCustomers).where(conditions.length ? and(...conditions) : undefined).orderBy(asc(crmCustomers.name)); const ids = new Set(customers.map((customer) => customer.id)); const [allSales, allInteractions, imports] = await Promise.all([db.select().from(crmSales).orderBy(desc(crmSales.saleDate)), db.select().from(crmInteractions).orderBy(desc(crmInteractions.contactedAt), desc(crmInteractions.id)), db.select().from(crmImports).orderBy(desc(crmImports.createdAt))]); return Response.json({ user: access, customers, sales: allSales.filter((row) => row.customerId && ids.has(row.customerId)), interactions: allInteractions.filter((row) => ids.has(row.customerId)), imports: access.role === "admin" ? imports : imports.filter((item) => item.createdBy === access.email) }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao carregar o CRM." }, { status: 500 }); } }

export async function POST(request: Request) { try { const access = await getCurrentAccess(); const denied = accessError(access, ["admin","vendedora"]); if (denied || !access) return denied!; const body = await request.json() as Record<string, unknown>, action = text(body.action), db = getDb();
  if (action === "customer") { const name = text(body.name); if (!name) return Response.json({ error: "Informe o nome da cliente." }, { status: 400 }); const responsibleSeller = access.role === "vendedora" ? access.sellerName : text(body.responsibleSeller) || null; const [row] = await db.insert(crmCustomers).values({ externalCode: text(body.externalCode) || null, name, cpf: text(body.cpf) || null, birthDate: text(body.birthDate) || null, phone: text(body.phone) || null, email: text(body.email) || null, city: text(body.city) || null, state: text(body.state) || null, responsibleSeller, firstPurchaseAt: text(body.firstPurchaseAt) || null, lastPurchaseAt: text(body.lastPurchaseAt) || text(body.firstPurchaseAt) || null }).returning(); return Response.json({ row }, { status: 201 }); }
  if (action === "interaction") { const customerId = num(body.customerId); const [customer] = await db.select().from(crmCustomers).where(eq(crmCustomers.id, customerId)).limit(1); if (!customer || (access.role === "vendedora" && customer.responsibleSeller !== access.sellerName)) return Response.json({ error: "Cliente não encontrada." }, { status: 404 }); const status = text(body.status) || "contacted", contactedAt = text(body.contactedAt) || new Date().toISOString().slice(0,10), nextContactAt = text(body.nextContactAt) || null, note = text(body.note); if (!note) return Response.json({ error: "Escreva uma observação sobre o contato." }, { status: 400 }); const [row] = await db.insert(crmInteractions).values({ customerId, userEmail: access.email, status, note, contactedAt, nextContactAt }).returning(); await db.update(crmCustomers).set({ status, nextContactAt, updatedAt: sql`CURRENT_TIMESTAMP` }).where(eq(crmCustomers.id, customerId)); return Response.json({ row }, { status: 201 }); }
  if (action === "import") { const reportType = text(body.reportType), fileName = text(body.fileName), reportMonth = text(body.reportMonth) || null, rows = Array.isArray(body.rows) ? body.rows as Record<string, unknown>[] : []; if (!rows.length || !["first_purchase","birthdays","sales_by_seller"].includes(reportType)) return Response.json({ error: "Importação inválida." }, { status: 400 }); const batch = crypto.randomUUID(); let imported = 0, skipped = 0; const customers = await db.select().from(crmCustomers); const byCode = new Map(customers.filter((item) => item.externalCode).map((item) => [item.externalCode!, item])); const byName = new Map<string, typeof customers>(); for (const customer of customers) { const key = normalize(customer.name); byName.set(key, [...(byName.get(key) || []), customer]); }
    if (reportType === "first_purchase") for (const raw of rows) { const seller = text(raw.sellerName); if (access.role === "vendedora" && seller !== access.sellerName) { skipped++; continue; } const code = text(raw.externalCode), name = text(raw.name); if (!code || !name) { skipped++; continue; } const values = { name, phone: text(raw.phone) || null, city: text(raw.city) || null, state: text(raw.state) || null, responsibleSeller: seller || (access.role === "vendedora" ? access.sellerName : null), firstPurchaseAt: text(raw.firstPurchaseAt) || null, lastPurchaseAt: text(raw.firstPurchaseAt) || null, piecesCount: num(raw.piecesCount), totalSpent: num(raw.totalSpent), purchaseCount: 1, updatedAt: new Date().toISOString() }; const existing = byCode.get(code); if (existing) await db.update(crmCustomers).set(values).where(eq(crmCustomers.id, existing.id)); else { const [created] = await db.insert(crmCustomers).values({ externalCode: code, ...values }).returning(); byCode.set(code, created); byName.set(normalize(name), [...(byName.get(normalize(name)) || []), created]); } imported++; }
    if (reportType === "birthdays") for (const raw of rows) { const code = text(raw.externalCode), name = text(raw.name), existing = byCode.get(code); if (access.role === "vendedora" && (!existing || existing.responsibleSeller !== access.sellerName)) { skipped++; continue; } const values = { name, cpf: text(raw.cpf) || null, birthDate: text(raw.birthDate) || null, phone: text(raw.phone) || null, phone2: text(raw.phone2) || null, email: text(raw.email) || null, city: text(raw.city) || null, state: text(raw.state) || null, updatedAt: new Date().toISOString() }; if (existing) await db.update(crmCustomers).set(values).where(eq(crmCustomers.id, existing.id)); else if (access.role === "admin" && code && name) { const [created] = await db.insert(crmCustomers).values({ externalCode: code, ...values }).returning(); byCode.set(code, created); byName.set(normalize(name), [...(byName.get(normalize(name)) || []), created]); } else { skipped++; continue; } imported++; }
    if (reportType === "sales_by_seller") for (const raw of rows) { const sellerName = text(raw.sellerName); if (access.role === "vendedora" && sellerName !== access.sellerName) { skipped++; continue; } const matches = byName.get(normalize(text(raw.customerName))) || [], customer = matches.length === 1 ? matches[0] : null, saleCode = text(raw.saleCode); if (!saleCode) { skipped++; continue; } await db.insert(crmSales).values({ saleCode, customerId: customer?.id || null, customerName: text(raw.customerName), sellerName, saleDate: text(raw.saleDate), amount: num(raw.amount), productValue: num(raw.productValue), exchangeValue: num(raw.exchangeValue), variationValue: num(raw.variationValue), importBatch: batch }).onConflictDoUpdate({ target: crmSales.saleCode, set: { customerId: customer?.id || null, customerName: text(raw.customerName), sellerName, saleDate: text(raw.saleDate), amount: num(raw.amount), productValue: num(raw.productValue), exchangeValue: num(raw.exchangeValue), variationValue: num(raw.variationValue), importBatch: batch } }); imported++; }
    const updatedCustomers = await db.select().from(crmCustomers); const allSales = await db.select().from(crmSales); for (const customer of updatedCustomers) { const customerSales = allSales.filter((sale) => sale.customerId === customer.id); if (!customerSales.length) continue; await db.update(crmCustomers).set({ lastPurchaseAt: customerSales.reduce((last, sale) => sale.saleDate > last ? sale.saleDate : last, customerSales[0].saleDate), purchaseCount: customerSales.length, totalSpent: customerSales.reduce((sum, sale) => sum + sale.amount, 0), updatedAt: sql`CURRENT_TIMESTAMP` }).where(eq(crmCustomers.id, customer.id)); }
    await db.insert(crmImports).values({ importBatch: batch, fileName, reportType, reportMonth, recordCount: imported, createdBy: access.email }); return Response.json({ imported, skipped, batch }); }
  if (action === "import_delete") { const batch = text(body.importBatch); const [record] = await db.select().from(crmImports).where(eq(crmImports.importBatch, batch)).limit(1); if (!record || (access.role !== "admin" && record.createdBy !== access.email)) return Response.json({ error: "Importação não encontrada." }, { status: 404 }); await db.delete(crmSales).where(eq(crmSales.importBatch, batch)); await db.delete(crmImports).where(eq(crmImports.importBatch, batch)); return Response.json({ deleted: true }); }
  return Response.json({ error: "Ação inválida." }, { status: 400 });
} catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao salvar no CRM." }, { status: 500 }); } }
