import { and, asc, desc, eq, gte, like, lte, sql } from "drizzle-orm";
import { headers } from "next/headers";
import { getDb } from "@/db";
import { productionModelTracking, receipts } from "@/db/schema";
export const dynamic = "force-dynamic";
async function currentUser() { const h = await headers(); const email = h.get("oai-authenticated-user-email"); const encoded = h.get("oai-authenticated-user-full-name"); const name = encoded && h.get("oai-authenticated-user-full-name-encoding") === "percent-encoded-utf-8" ? decodeURIComponent(encoded) : email?.split("@")[0] ?? "Administrador Coreto"; return { name, email, role: "admin" as const }; }
export async function GET(request: Request) { try { const url = new URL(request.url); const conditions = []; const from = url.searchParams.get("from"), to = url.searchParams.get("to"), model = url.searchParams.get("model"), color = url.searchParams.get("color"); if (from) conditions.push(gte(receipts.receivedAt, from)); if (to) conditions.push(lte(receipts.receivedAt, to)); if (model) conditions.push(like(receipts.model, `%${model}%`)); if (color) conditions.push(like(receipts.color, `%${color}%`)); const db = getDb(); const rows = await db.select().from(receipts).where(conditions.length ? and(...conditions) : undefined).orderBy(desc(receipts.receivedAt), desc(receipts.createdAt), desc(receipts.id)).limit(500); const models = await db.selectDistinct({ model: receipts.model }).from(receipts).orderBy(asc(receipts.model)); const tracking = await db.select().from(productionModelTracking).orderBy(asc(productionModelTracking.model)); return Response.json({ receipts: rows, models: models.map((i) => i.model), tracking, user: await currentUser() }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao consultar recebimentos." }, { status: 500 }); } }
export async function POST(request: Request) { try { const body = await request.json() as { receivedAt?: string; model?: string; color?: string; size?: string; quantity?: number; observation?: string; items?: { color?: string; size?: string; quantity?: number }[] }; const sourceItems = Array.isArray(body.items) ? body.items : [{ color: body.color, size: body.size, quantity: body.quantity }]; if (!body.receivedAt || !body.model?.trim() || !sourceItems.length) return Response.json({ error: "Dados do recebimento inválidos." }, { status: 400 }); const items = sourceItems.map((item) => ({ color: item.color?.trim() || "", size: item.size?.trim() || "", quantity: Number(item.quantity) })); if (items.some((item) => !item.color || !item.size || !Number.isInteger(item.quantity) || item.quantity < 1)) return Response.json({ error: "Revise as cores, tamanhos e quantidades informadas." }, { status: 400 }); const user = await currentUser(), values = items.map((item) => ({ receivedAt: body.receivedAt!, model: body.model!.trim(), color: item.color, size: item.size, quantity: item.quantity, checkedBy: user.name, checkedByEmail: user.email, observation: body.observation?.trim() || null })), created: typeof values = []; for (let index = 0; index < values.length; index += 8) created.push(...await getDb().insert(receipts).values(values.slice(index, index + 8)).returning()); return Response.json({ receipt: created[0], receipts: created }, { status: 201 }); } catch { return Response.json({ error: "Não foi possível salvar este recebimento. Tente novamente." }, { status: 500 }); } }
export async function PATCH(request: Request) { try { const body = await request.json() as { id?: number; quantity?: number; observation?: string }; const id = Number(body.id), quantity = Number(body.quantity); if (!Number.isInteger(id) || id < 1 || !Number.isInteger(quantity) || quantity < 1) return Response.json({ error: "Revise a quantidade informada." }, { status: 400 }); const [updated] = await getDb().update(receipts).set({ quantity, observation: body.observation?.trim() || null }).where(eq(receipts.id, id)).returning(); if (!updated) return Response.json({ error: "Recebimento não encontrado." }, { status: 404 }); return Response.json({ receipt: updated }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Não foi possível corrigir o recebimento." }, { status: 500 }); } }
export async function PUT(request: Request) { try { const body = await request.json() as { model?: string; status?: string; pendingNote?: string }; const model = body.model?.trim(); const status = body.status === "completed" ? "completed" : "pending"; if (!model) return Response.json({ error: "Modelo inválido." }, { status: 400 }); const pendingNote = body.pendingNote?.trim() || null; const [tracking] = await getDb().insert(productionModelTracking).values({ model, status, pendingNote }).onConflictDoUpdate({ target: productionModelTracking.model, set: { status, pendingNote, updatedAt: sql`CURRENT_TIMESTAMP` } }).returning(); return Response.json({ tracking }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao atualizar o acompanhamento." }, { status: 500 }); } }
export async function DELETE(request: Request) { try { const id = Number(new URL(request.url).searchParams.get("id")); if (!Number.isInteger(id) || id < 1) return Response.json({ error: "Recebimento inválido." }, { status: 400 }); const [deleted] = await getDb().delete(receipts).where(eq(receipts.id, id)).returning(); if (!deleted) return Response.json({ error: "Recebimento não encontrado." }, { status: 404 }); return Response.json({ deleted: true }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao excluir o recebimento." }, { status: 500 }); } }
